import type { Scene } from "@shared/immersiveSceneTypes";

export const IMMERSIVE_VOICE_REFERENCE = {
  sceneId: "beach",
  teacherName: "James",
  language: "en-US",
  gender: "male" as const,
} as const;

/**
 * Catálogo de prévias visuais. Falas, vocabulário, hotspots e diálogos são
 * buscados exclusivamente por procedimentos autenticados após a autorização.
 */
export const IMMERSIVE_SCENES: Scene[] = [
  { id: "paris", name: "Paris, França", nameEn: "Paris Street", flag: "🇫🇷", bgImage: "/manus-storage/scene_paris_40173c5c.jpg", teacherImage: "/manus-storage/prof_sophie_a6324ef6.png", teacherName: "Sophie", teacherLang: "fr-FR", langCode: "fr", teacherGender: "female", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "beach", name: "Praia Tropical", nameEn: "Tropical Beach", flag: "🌊", bgImage: "/manus-storage/scene_beach_b760e0e7.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", teacherAnimation: "professor-wave", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "forest", name: "Floresta Encantada", nameEn: "Enchanted Forest", flag: "🌲", bgImage: "/manus-storage/scene_forest_8d87f524.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "tokyo", name: "Tóquio, Japão", nameEn: "Tokyo, Japan", flag: "🇯🇵", bgImage: "/manus-storage/scene_tokyo_fd6d9ada.jpg", teacherImage: "/manus-storage/prof_yuki_ae657681.png", teacherName: "Yuki", teacherLang: "ja-JP", langCode: "ja", teacherGender: "female", difficulty: "advanced", premium: true, dialog: [], hotspots: [] },
  { id: "newyork", name: "Nova York, EUA", nameEn: "New York City", flag: "🇺🇸", bgImage: "/manus-storage/scene_newyork_40ef7561.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "kitchen", name: "Cozinha Moderna", nameEn: "Modern Kitchen", flag: "🍳", bgImage: "/manus-storage/scene_kitchen_305d6ac6.jpg", teacherImage: "/manus-storage/prof_carlos_3a763932.jpg", teacherName: "Carlos", teacherLang: "es-ES", langCode: "es", teacherGender: "male", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "restaurant", name: "Restaurante Brasileiro", nameEn: "Brazilian Restaurant", flag: "🇧🇷", bgImage: "/manus-storage/scene_restaurant_d7d3f766.jpg", teacherImage: "/manus-storage/prof_ana_241ffde7.png", teacherName: "Ana", teacherLang: "pt-BR", langCode: "pt", teacherGender: "female", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "airport", name: "Aeroporto Internacional", nameEn: "International Airport", flag: "✈️", bgImage: "/manus-storage/scene_airport_843d9307.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "hotel", name: "Hotel de Luxo", nameEn: "Luxury Hotel", flag: "🏨", bgImage: "/manus-storage/scene_hotel_8fff9928.jpg", teacherImage: "/manus-storage/prof_giulia_f8adfeb6.png", teacherName: "Giulia", teacherLang: "it-IT", langCode: "it", teacherGender: "female", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "supermarket", name: "Supermercado", nameEn: "Supermarket", flag: "🛒", bgImage: "/manus-storage/scene_supermarket_31f4bb92.jpg", teacherImage: "/manus-storage/prof_carlos_3a763932.jpg", teacherName: "Carlos", teacherLang: "es-ES", langCode: "es", teacherGender: "male", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "school", name: "Sala de Aula", nameEn: "Classroom", flag: "📚", bgImage: "/manus-storage/scene_school_8568b950.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "hospital", name: "Hospital", nameEn: "Hospital", flag: "🏥", bgImage: "/manus-storage/scene_hospital_891a1727.jpg", teacherImage: "/manus-storage/prof_priya_7c36613d.png", teacherName: "Priya", teacherLang: "en-GB", langCode: "en", teacherGender: "female", difficulty: "intermediate", premium: true, dialog: [], hotspots: [] },
  { id: "park", name: "Parque da Cidade", nameEn: "City Park", flag: "🌳", bgImage: "/manus-storage/scene_park_22801348.jpg", teacherImage: "/manus-storage/prof_sophie_a6324ef6.png", teacherName: "Sophie", teacherLang: "fr-FR", langCode: "fr", teacherGender: "female", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "mountain", name: "Montanha Nevada", nameEn: "Snowy Mountain", flag: "🏔️", bgImage: "/manus-storage/scene_mountain_531032d0.jpg", teacherImage: "/manus-storage/prof_hans_62b758a6.png", teacherName: "Hans", teacherLang: "de-DE", langCode: "de", teacherGender: "male", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "desert", name: "Deserto do Saara", nameEn: "Sahara Desert", flag: "🏜️", bgImage: "/manus-storage/scene_desert_667d9a87.jpg", teacherImage: "/manus-storage/prof_omar_5c108d44.png", teacherName: "Omar", teacherLang: "ar-SA", langCode: "ar", teacherGender: "male", difficulty: "advanced", premium: true, dialog: [], hotspots: [] },
  { id: "farm", name: "Fazenda Campestre", nameEn: "Country Farm", flag: "🌾", bgImage: "/manus-storage/scene_farm_2fb3b2ba.jpg", teacherImage: "/manus-storage/prof_maja_860515c8.png", teacherName: "Maja", teacherLang: "pl-PL", langCode: "pl", teacherGender: "female", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "museum", name: "Museu de Arte", nameEn: "Art Museum", flag: "🎨", bgImage: "/manus-storage/scene_museum_36dd2df4.jpg", teacherImage: "/manus-storage/prof_giulia_f8adfeb6.png", teacherName: "Giulia", teacherLang: "it-IT", langCode: "it", teacherGender: "female", difficulty: "advanced", premium: true, dialog: [], hotspots: [] },
  { id: "cinema", name: "Cinema Moderno", nameEn: "Modern Cinema", flag: "🎬", bgImage: "/manus-storage/scene_cinema_9a35c5af.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "gym", name: "Academia de Ginástica", nameEn: "Fitness Gym", flag: "💪", bgImage: "/manus-storage/scene_gym_f96cac6f.jpg", teacherImage: "/manus-storage/prof_emre_78eb8ccb.png", teacherName: "Emre", teacherLang: "tr-TR", langCode: "tr", teacherGender: "male", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "library", name: "Biblioteca", nameEn: "Library", flag: "📚", bgImage: "/manus-storage/scene_library_732f048d.jpg", teacherImage: "/manus-storage/prof_maja_860515c8.png", teacherName: "Maja", teacherLang: "pl-PL", langCode: "pl", teacherGender: "female", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "office", name: "Escritório Moderno", nameEn: "Modern Office", flag: "💼", bgImage: "/manus-storage/scene_office_7981f124.jpg", teacherImage: "/manus-storage/prof_ivan_5c4962f5.png", teacherName: "Ivan", teacherLang: "ru-RU", langCode: "ru", teacherGender: "male", difficulty: "intermediate", premium: true, dialog: [], hotspots: [] },
  { id: "metro", name: "Metrô de Paris", nameEn: "Paris Metro", flag: "🚇", bgImage: "/manus-storage/scene_metro_5fffc615.jpg", teacherImage: "/manus-storage/prof_sophie_a6324ef6.png", teacherName: "Sophie", teacherLang: "fr-FR", langCode: "fr", teacherGender: "female", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "port", name: "Porto Mediterrâneo", nameEn: "Mediterranean Port", flag: "⛵", bgImage: "/manus-storage/scene_port_e35f99dc.jpg", teacherImage: "/manus-storage/prof_giulia_f8adfeb6.png", teacherName: "Giulia", teacherLang: "it-IT", langCode: "it", teacherGender: "female", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "medieval", name: "Mercado Medieval", nameEn: "Medieval Market", flag: "🏰", bgImage: "/manus-storage/scene_medieval_402d8fa3.jpg", teacherImage: "/manus-storage/prof_hans_62b758a6.png", teacherName: "Hans", teacherLang: "de-DE", langCode: "de", teacherGender: "male", difficulty: "advanced", premium: true, dialog: [], hotspots: [] },
  { id: "spa", name: "Spa & Bem-Estar", nameEn: "Spa & Wellness", flag: "🧘", bgImage: "/manus-storage/scene_spa_abacc5aa.jpg", teacherImage: "/manus-storage/prof_priya_7c36613d.png", teacherName: "Priya", teacherLang: "en-GB", langCode: "en", teacherGender: "female", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
  { id: "garden", name: "Jardim Japonês", nameEn: "Japanese Garden", flag: "🌸", bgImage: "/manus-storage/scene_garden_77e79005.jpg", teacherImage: "/manus-storage/prof_yuki_ae657681.png", teacherName: "Yuki", teacherLang: "ja-JP", langCode: "ja", teacherGender: "female", difficulty: "advanced", premium: true, dialog: [], hotspots: [] },
  { id: "cafe", name: "Café Parisiense", nameEn: "Parisian Café", flag: "☕", bgImage: "/manus-storage/scene_cafe_ab4e0305.jpg", teacherImage: "/manus-storage/prof_sophie_a6324ef6.png", teacherName: "Sophie", teacherLang: "fr-FR", langCode: "fr", teacherGender: "female", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "family_home", name: "Casa da Família", nameEn: "Family at Home", flag: "🏠", bgImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663082627627/2PrAxuVNSTauUZFfMWq3zJ/scene_family_home-o3WNxh4WSTa7fkpvh4ALxF.webp", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "beginner", premium: false, dialog: [], hotspots: [] },
  { id: "airport_family", name: "Família no Aeroporto", nameEn: "Family at Airport", flag: "✈️🏠", bgImage: "/manus-storage/scene_airport_family_005d0f25.jpg", teacherImage: "/manus-storage/prof_james_b9f2fff7.png", teacherName: "James", teacherLang: "en-US", langCode: "en", teacherGender: "male", difficulty: "intermediate", premium: false, dialog: [], hotspots: [] },
];
