import type { Scene } from "@shared/immersiveSceneTypes";

export const IMMERSIVE_VOICE_REFERENCE = {
  sceneId: "beach",
  teacherName: "James",
  language: "en-US",
  gender: "male" as const,
} as const;

export const IMMERSIVE_SCENES: Scene[] = [
  {
    id:"paris", name:"Paris, França", nameEn:"Paris Street", flag:"🇫🇷",
    bgImage:"/manus-storage/scene_paris_40173c5c.jpg",
    teacherImage:"/manus-storage/prof_sophie_a6324ef6.png",
    teacherName:"Sophie", teacherLang:"fr-FR", langCode:"fr", teacherGender:"female",
    teacherGreeting:"Bienvenue à Paris! Cliquez sur les objets pour apprendre!",
    greetingPt:"Bem-vindo a Paris! Clique nos objetos para aprender!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"beach", name:"Praia Tropical", nameEn:"Tropical Beach", flag:"🌊",
    bgImage:"/manus-storage/scene_beach_b760e0e7.jpg",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherAnimation: "professor-wave",
    teacherGreeting:"Welcome to the beach! Click the objects to learn!",
    greetingPt:"Bem-vindo à praia! Clique nos objetos para aprender!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"forest", name:"Floresta Encantada", nameEn:"Enchanted Forest", flag:"🌲",
    bgImage:"/manus-storage/scene_forest_8d87f524.jpg",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"Welcome to the Enchanted Forest! Click the objects to learn!",
    greetingPt:"Bem-vindo à Floresta Encantada! Clique nos objetos para aprender!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"tokyo", name:"Tóquio, Japão", nameEn:"Tokyo, Japan", flag:"🇯🇵",
    bgImage:"/manus-storage/scene_tokyo_fd6d9ada.jpg",
    teacherImage:"/manus-storage/prof_yuki_ae657681.png",
    teacherName:"Yuki", teacherLang:"ja-JP", langCode:"ja", teacherGender:"female",
    teacherGreeting:"東京へようこそ！オブジェクトをクリックして学びましょう！",
    greetingPt:"Bem-vindo a Tóquio! Clique nos objetos para aprender!",
    difficulty:"advanced", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"newyork", name:"Nova York, EUA", nameEn:"New York City", flag:"🇺🇸",
    bgImage:"/manus-storage/scene_newyork_40ef7561.jpg",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"Welcome to New York! Click the objects to learn!",
    greetingPt:"Bem-vindo a Nova York! Clique nos objetos para aprender!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"kitchen", name:"Cozinha Moderna", nameEn:"Modern Kitchen", flag:"🍳",
    bgImage:"/manus-storage/scene_kitchen_305d6ac6.jpg",
    teacherImage:"/manus-storage/prof_carlos_3a763932.jpg",
    teacherName:"Carlos", teacherLang:"es-ES", langCode:"es", teacherGender:"male",
    teacherGreeting:"¡Bienvenido a la cocina! ¡Haz clic en los objetos para aprender!",
    greetingPt:"Bem-vindo à cozinha! Clique nos objetos para aprender!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"restaurant", name:"Restaurante Brasileiro", nameEn:"Brazilian Restaurant", flag:"🇧🇷",
    bgImage:"/manus-storage/scene_restaurant_d7d3f766.jpg",
    teacherImage:"/manus-storage/prof_ana_241ffde7.png",
    teacherName:"Ana", teacherLang:"pt-BR", langCode:"pt", teacherGender:"female",
    teacherGreeting:"Bem-vindo ao restaurante! Clique nos objetos para aprender!",
    greetingPt:"Bem-vindo ao restaurante! Clique nos objetos para aprender!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"airport", name:"Aeroporto Internacional", nameEn:"International Airport", flag:"✈️",
    bgImage:"/manus-storage/scene_airport_843d9307.jpg",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"Welcome to the airport! Let's learn travel vocabulary!",
    greetingPt:"Bem-vindo ao aeroporto! Vamos aprender vocabulário de viagem!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"hotel", name:"Hotel de Luxo", nameEn:"Luxury Hotel", flag:"🏨",
    bgImage:"/manus-storage/scene_hotel_8fff9928.jpg",
    teacherImage:"/manus-storage/prof_giulia_f8adfeb6.png",
    teacherName:"Giulia", teacherLang:"it-IT", langCode:"it", teacherGender:"female",
    teacherGreeting:"Benvenuto in hotel! Impariamo le parole dell'hotel!",
    greetingPt:"Bem-vindo ao hotel! Vamos aprender palavras do hotel!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"supermarket", name:"Supermercado", nameEn:"Supermarket", flag:"🛒",
    bgImage:"/manus-storage/scene_supermarket_31f4bb92.jpg",
    teacherImage:"/manus-storage/prof_carlos_3a763932.jpg",
    teacherName:"Carlos", teacherLang:"es-ES", langCode:"es", teacherGender:"male",
    teacherGreeting:"¡Bienvenido al supermercado! ¡Aprendamos a hacer compras!",
    greetingPt:"Bem-vindo ao supermercado! Vamos aprender a fazer compras!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"school", name:"Sala de Aula", nameEn:"Classroom", flag:"📚",
    bgImage:"/manus-storage/scene_school_8568b950.jpg",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"Welcome to the classroom! Let's study together!",
    greetingPt:"Bem-vindo à sala de aula! Vamos estudar juntos!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"hospital", name:"Hospital", nameEn:"Hospital", flag:"🏥",
    bgImage:"/manus-storage/scene_hospital_891a1727.jpg",
    teacherImage:"/manus-storage/prof_priya_7c36613d.png",
    teacherName:"Priya", teacherLang:"en-GB", langCode:"en", teacherGender:"female",
    teacherGreeting:"Welcome to the hospital! Learn medical vocabulary!",
    greetingPt:"Bem-vindo ao hospital! Aprenda vocabulário médico!",
    difficulty:"intermediate", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"park", name:"Parque da Cidade", nameEn:"City Park", flag:"🌳",
    bgImage:"/manus-storage/scene_park_22801348.jpg",
    teacherImage:"/manus-storage/prof_sophie_a6324ef6.png",
    teacherName:"Sophie", teacherLang:"fr-FR", langCode:"fr", teacherGender:"female",
    teacherGreeting:"Bienvenue au parc! Profitons de la nature!",
    greetingPt:"Bem-vindo ao parque! Vamos aproveitar a natureza!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"mountain", name:"Montanha Nevada", nameEn:"Snowy Mountain", flag:"🏔️",
    bgImage:"/manus-storage/scene_mountain_531032d0.jpg",
    teacherImage:"/manus-storage/prof_hans_62b758a6.png",
    teacherName:"Hans", teacherLang:"de-DE", langCode:"de", teacherGender:"male",
    teacherGreeting:"Willkommen auf dem Berg! Lernen wir Natur-Vokabular!",
    greetingPt:"Bem-vindo à montanha! Vamos aprender vocabulário da natureza!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"desert", name:"Deserto do Saara", nameEn:"Sahara Desert", flag:"🏜️",
    bgImage:"/manus-storage/scene_desert_667d9a87.jpg",
    teacherImage:"/manus-storage/prof_omar_5c108d44.png",
    teacherName:"Omar", teacherLang:"ar-SA", langCode:"ar", teacherGender:"male",
    teacherGreeting:"مرحباً بك في الصحراء! دعنا نتعلم المفردات!",
    greetingPt:"Bem-vindo ao deserto! Vamos aprender vocabulário!",
    difficulty:"advanced", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"farm", name:"Fazenda Campestre", nameEn:"Country Farm", flag:"🌾",
    bgImage:"/manus-storage/scene_farm_2fb3b2ba.jpg",
    teacherImage:"/manus-storage/prof_maja_860515c8.png",
    teacherName:"Maja", teacherLang:"pl-PL", langCode:"pl", teacherGender:"female",
    teacherGreeting:"Witaj na farmie! Uczmy się słownictwa wiejskiego!",
    greetingPt:"Bem-vindo à fazenda! Vamos aprender vocabulário rural!",
    difficulty:"intermediate", premium:false,
    dialog:[],
    hotspots:[]
  },
  {
    id:"museum", name:"Museu de Arte", nameEn:"Art Museum", flag:"🎨",
    bgImage:"/manus-storage/scene_museum_36dd2df4.jpg",
    teacherImage:"/manus-storage/prof_giulia_f8adfeb6.png",
    teacherName:"Giulia", teacherLang:"it-IT", langCode:"it", teacherGender:"female",
    teacherGreeting:"Benvenuto al museo! Scopriamo l'arte insieme!",
    greetingPt:"Bem-vindo ao museu! Vamos descobrir a arte juntos!",
    difficulty:"advanced", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"cinema", name:"Cinema Moderno", nameEn:"Modern Cinema", flag:"🎬",
    bgImage:"/manus-storage/scene_cinema_9a35c5af.jpg",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"Welcome to the cinema! Let's learn movie vocabulary!",
    greetingPt:"Bem-vindo ao cinema! Vamos aprender vocabulário de filmes!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"gym", name:"Academia de Ginástica", nameEn:"Fitness Gym", flag:"💪",
    bgImage:"/manus-storage/scene_gym_f96cac6f.jpg",
    teacherImage:"/manus-storage/prof_emre_78eb8ccb.png",
    teacherName:"Emre", teacherLang:"tr-TR", langCode:"tr", teacherGender:"male",
    teacherGreeting:"Spor salonuna hoş geldiniz! Spor kelimelerini öğrenelim!",
    greetingPt:"Bem-vindo à academia! Vamos aprender vocabulário de esportes!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"library", name:"Biblioteca", nameEn:"Library", flag:"📚",
    bgImage:"/manus-storage/scene_library_732f048d.jpg",
    teacherImage:"/manus-storage/prof_maja_860515c8.png",
    teacherName:"Maja", teacherLang:"pl-PL", langCode:"pl", teacherGender:"female",
    teacherGreeting:"Witaj w bibliotece! Czytajmy razem!",
    greetingPt:"Bem-vindo à biblioteca! Vamos ler juntos!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"office", name:"Escritório Moderno", nameEn:"Modern Office", flag:"💼",
    bgImage:"/manus-storage/scene_office_7981f124.jpg",
    teacherImage:"/manus-storage/prof_ivan_5c4962f5.png",
    teacherName:"Ivan", teacherLang:"ru-RU", langCode:"ru", teacherGender:"male",
    teacherGreeting:"Добро пожаловать в офис! Учим деловую лексику!",
    greetingPt:"Bem-vindo ao escritório! Vamos aprender vocabulário de negócios!",
    difficulty:"intermediate", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"metro", name:"Metrô de Paris", nameEn:"Paris Metro", flag:"🚇",
    bgImage:"/manus-storage/scene_metro_5fffc615.jpg",
    teacherImage:"/manus-storage/prof_sophie_a6324ef6.png",
    teacherName:"Sophie", teacherLang:"fr-FR", langCode:"fr", teacherGender:"female",
    teacherGreeting:"Bienvenue dans le métro! Apprenons à voyager!",
    greetingPt:"Bem-vindo ao metrô! Vamos aprender a viajar!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"port", name:"Porto Mediterrâneo", nameEn:"Mediterranean Port", flag:"⛵",
    bgImage:"/manus-storage/scene_port_e35f99dc.jpg",
    teacherImage:"/manus-storage/prof_giulia_f8adfeb6.png",
    teacherName:"Giulia", teacherLang:"it-IT", langCode:"it", teacherGender:"female",
    teacherGreeting:"Benvenuto al porto! Impariamo il vocabolario del mare!",
    greetingPt:"Bem-vindo ao porto! Vamos aprender vocabulário do mar!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"medieval", name:"Mercado Medieval", nameEn:"Medieval Market", flag:"🏰",
    bgImage:"/manus-storage/scene_medieval_402d8fa3.jpg",
    teacherImage:"/manus-storage/prof_hans_62b758a6.png",
    teacherName:"Hans", teacherLang:"de-DE", langCode:"de", teacherGender:"male",
    teacherGreeting:"Willkommen auf dem mittelalterlichen Markt! Lernen wir Geschichte!",
    greetingPt:"Bem-vindo ao mercado medieval! Vamos aprender história!",
    difficulty:"advanced", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"spa", name:"Spa & Bem-Estar", nameEn:"Spa & Wellness", flag:"🧘",
    bgImage:"/manus-storage/scene_spa_abacc5aa.jpg",
    teacherImage:"/manus-storage/prof_priya_7c36613d.png",
    teacherName:"Priya", teacherLang:"en-GB", langCode:"en", teacherGender:"female",
    teacherGreeting:"Welcome to the spa! Let's relax and learn wellness vocabulary!",
    greetingPt:"Bem-vindo ao spa! Vamos relaxar e aprender vocabulário de bem-estar!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"garden", name:"Jardim Japonês", nameEn:"Japanese Garden", flag:"🌸",
    bgImage:"/manus-storage/scene_garden_77e79005.jpg",
    teacherImage:"/manus-storage/prof_yuki_ae657681.png",
    teacherName:"Yuki", teacherLang:"ja-JP", langCode:"ja", teacherGender:"female",
    teacherGreeting:"日本庭園へようこそ！自然の中で学びましょう！",
    greetingPt:"Bem-vindo ao jardim japonês! Aprenda na natureza!",
    difficulty:"advanced", premium:true,
    dialog: [],
    hotspots: []
  },
  {
    id:"cafe", name:"Café Parisiense", nameEn:"Parisian Café", flag:"☕",
    bgImage:"/manus-storage/scene_cafe_ab4e0305.jpg",
    teacherImage:"/manus-storage/prof_sophie_a6324ef6.png",
    teacherName:"Sophie", teacherLang:"fr-FR", langCode:"fr", teacherGender:"female",
    teacherGreeting:"Bienvenue au café! Commandez en français!",
    greetingPt:"Bem-vindo ao café! Peça em francês!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"family_home", name:"Casa da Família", nameEn:"Family at Home", flag:"🏠",
    bgImage:"https://d2xsxph8kpxj0f.cloudfront.net/310519663082627627/2PrAxuVNSTauUZFfMWq3zJ/scene_family_home-o3WNxh4WSTa7fkpvh4ALxF.webp",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"Welcome home! Let's learn family vocabulary together!",
    greetingPt:"Bem-vindo à casa! Vamos aprender vocabulário de família juntos!",
    difficulty:"beginner", premium:false,
    dialog: [],
    hotspots: []
  },
  {
    id:"airport_family", name:"Família no Aeroporto", nameEn:"Family at Airport", flag:"✈️🏠",
    bgImage:"https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80",
    teacherImage:"/manus-storage/prof_james_b9f2fff7.png",
    teacherName:"James", teacherLang:"en-US", langCode:"en", teacherGender:"male",
    teacherGreeting:"The family is at the airport! Let's learn travel phrases!",
    greetingPt:"A família está no aeroporto! Vamos aprender frases de viagem!",
    difficulty:"intermediate", premium:false,
    dialog: [],
    hotspots: []
  },
];
