const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({
  section: "Preposições, phrasal verbs e conjunções",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const TWELFTH_BLOCK_PREPOSITIONS_PHRASALS_CONJUNCTIONS = [
  lesson("Preposições: localização, movimento e relação", "O original reúne muitas preposições porque elas organizam lugar, tempo, movimento e relação. Não procure uma tradução única: escolha pelo sentido que a frase exige.", "along, across, through, around, under, beneath, before, within, during, instead of, into, between, among, beyond, without", [["We walked along the road.", "Nós caminhamos ao longo da estrada.", "along: ao longo de"], ["The cat is beneath the chair.", "O gato está debaixo da cadeira.", "beneath: sob/debaixo de"], ["She went into the museum.", "Ela entrou no museu.", "into: movimento para dentro"]], "Escreva três frases: uma de caminho, uma de posição e uma de movimento para dentro. Diga em português qual relação cada preposição expressa.", ["She", "went", "into", "the", "museum"], "She went into the museum.", "No Pareto, recupere along, beneath, into, between, without e during; associe cada forma à relação que ela cria."),
  lesson("In, at e on: sentidos próximos, usos diferentes", "In costuma marcar interior ou períodos; at marca ponto específico; on marca superfície e também certos dias. O bloco mantém o contraste do original e corrige a expressão para in a few minutes.", "in a few minutes / in bed / at school / at home / on the wall / on the chair", [["I will be there in a few minutes.", "Estarei lá em alguns minutos.", "intervalo de tempo corrigido"], ["I will see you at school.", "Vejo você na escola.", "ponto específico"], ["The clock is on the wall.", "O relógio está na parede.", "superfície/contato"]], "Complete três frases próprias com in, at e on. Depois explique em pt-BR por que não são intercambiáveis nesses exemplos.", ["The", "clock", "is", "on", "the", "wall"], "The clock is on the wall.", "No Pareto, recupere in, at, on, minutes, school e wall; escolha tempo, ponto ou superfície antes de responder."),
  lesson("Phrasal verbs com come e go", "O original apresenta verbos com partículas como uso imediato. A partícula muda o sentido do verbo; por isso, aprenda a combinação completa e não apenas a tradução isolada de come ou go.", "come in / come down / go away / go on / go up / go off", [["Do you want to come in?", "Você quer entrar?", "come in: entrar"], ["John, come down for a moment.", "John, desça por um momento.", "come down: descer"], ["Go on with your life.", "Siga com a sua vida.", "go on: continuar"]], "Monte um mini-diálogo com uma entrada, um deslocamento e uma continuação usando três phrasal verbs do bloco.", ["Go", "on", "with", "your", "life"], "Go on with your life.", "No Pareto, recupere come in, come down, go away, go on, go up e go off; memorize cada combinação como uma unidade de sentido."),
  lesson("Phrasal verbs com take: ações concretas", "As combinações com take aparecem em frases cotidianas. O contexto ajuda a distinguir tirar, levar embora, levar para um lugar ou retirar algo de algum ponto.", "take away / take from / take off / take to", [["Take off your shoes.", "Tire seus sapatos.", "take off: tirar"], ["Please take the dog away from the kitchen.", "Por favor, leve o cachorro para longe da cozinha.", "take away + from corrigido"], ["She takes her child to school.", "Ela leva a criança dela à escola.", "take to: levar a"]], "Escreva três instruções úteis com take off, take away e take to. Use objetos ou lugares do seu cotidiano.", ["Take", "off", "your", "shoes"], "Take off your shoes.", "No Pareto, recupere take away, take from, take off, take to, shoes e kitchen; ligue cada combinação a uma ação observável."),
  lesson("Conjunções: unir ideias com precisão", "O original fecha este trecho com uma lista de conjunções. A reconstrução usa grupos funcionais: contraste, causa, condição, tempo e consequência, para que a lista se transforme em frase completa.", "although / because / if / unless / while / therefore / however / as well as / since", [["Although it was late, we continued studying.", "Embora estivesse tarde, continuamos estudando.", "contraste"], ["We stayed home because it was raining.", "Ficamos em casa porque estava chovendo.", "causa"], ["If you finish early, call me.", "Se você terminar cedo, ligue para mim.", "condição"]], "Escreva quatro períodos: contraste com although, causa com because, condição com if e sequência temporal com while. Leia cada conexão em voz alta com áudio nativo.", ["If", "you", "finish", "early", "call", "me"], "If you finish early, call me.", "No Pareto, recupere although, because, if, while, however e therefore; nomeie a relação entre as duas ideias antes de montar o período."),
];
