const lesson = (
  title: string,
  explanation: string,
  languageFocus: string,
  examples: Array<[string, string, string]>,
  writingPrompt: string,
  scrambled: string[],
  answer: string,
  paretoPrompt: string,
) => ({
  section: "Alimentos, quantidade e auxiliares",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const EIGHTH_BLOCK_QUANTIFIERS_AND_AUXILIARIES = [
  lesson(
    "Alimentos contáveis e não contáveis",
    "Alguns alimentos podem ser contados diretamente, como eggs e apples. Outros são tratados como massa ou substância, como water, milk, rice e coffee. Para contar estes últimos, use um recipiente ou medida: a glass of water, two cups of coffee.",
    "Countable: an egg, two apples. Uncountable: water, milk, rice, coffee. Use a/an apenas com um item contável no singular.",
    [["I have an apple.", "Eu tenho uma maçã.", "item contável singular"], ["We need some rice.", "Nós precisamos de arroz.", "alimento não contável"], ["There are two cups of coffee on the table.", "Há duas xícaras de café sobre a mesa.", "recipiente torna a quantidade contável"]],
    "Escreva duas frases: uma com alimento contável e outra com alimento não contável. Em uma delas, use uma medida como a cup of ou a glass of.",
    ["have", "I", "an", "apple"],
    "I have an apple.",
    "No Pareto, recupere apple, egg, water, rice, cup e glass; classifique o que se conta diretamente e o que precisa de medida.",
  ),
  lesson(
    "Some, any e no em contexto",
    "Some é comum em afirmações e em ofertas ou pedidos educados. Any aparece sobretudo em perguntas e negativas. No já traz a ideia negativa e não deve ser combinado com not na mesma frase.",
    "There is some soup. / Is there any milk? / There is not any milk. / There is no milk.",
    [["There is some soup on the table.", "Há um pouco de sopa sobre a mesa.", "afirmação"], ["Is there any milk in the refrigerator?", "Há leite na geladeira?", "pergunta"], ["There is no salt in the jar.", "Não há sal no pote.", "no já é negativo"]],
    "Escreva uma afirmação com some, uma pergunta com any e uma negativa com no. Não use no e not juntos.",
    ["there", "Is", "any", "milk", "in", "the", "refrigerator"],
    "Is there any milk in the refrigerator?",
    "No Pareto, recupere some, any, no, soup, milk e salt; escolha a palavra de quantidade pela intenção da frase.",
  ),
  lesson(
    "There is: existe uma coisa ou uma quantidade não contável",
    "Use there is para dizer que uma coisa existe ou está em um lugar. A forma também acompanha alimento não contável, porque ele é tratado como uma quantidade geral: There is water.",
    "There is + singular ou não contável: There is a watermelon. There is some water.",
    [["There is a watermelon on the table.", "Há uma melancia sobre a mesa.", "singular"], ["There is some water in the bottle.", "Há água na garrafa.", "não contável"], ["Is there any soup? Yes, there is.", "Há sopa? Sim, há.", "pergunta e resposta curta"]],
    "Descreva três itens de uma mesa ou cozinha imaginada. Inclua uma frase com a/an e outra com um alimento não contável.",
    ["There", "is", "some", "water", "in", "the", "bottle"],
    "There is some water in the bottle.",
    "No Pareto, recupere there is, bottle, table, water e soup; diga o que existe em uma cozinha imaginada.",
  ),
  lesson(
    "There are: existem várias coisas",
    "Use there are quando a coisa principal está no plural. Compare o substantivo antes de escolher o verbo: one orange pede is; two oranges pedem are.",
    "There are + plural: There are oranges. There are not any potatoes. Are there any eggs?",
    [["There are some pears on the table.", "Há algumas peras sobre a mesa.", "plural afirmativo"], ["There are not any potatoes.", "Não há batatas.", "plural negativo"], ["Are there any oranges? Yes, there are.", "Há laranjas? Sim, há.", "pergunta e resposta curta"]],
    "Crie uma pergunta com Are there any…? e responda. Depois escreva uma frase negativa com There are not any….",
    ["there", "Are", "any", "oranges"],
    "Are there any oranges?",
    "No Pareto, recupere there are, pears, potatoes, oranges e eggs; separe frases de uma coisa e de várias coisas.",
  ),
  lesson(
    "Be no presente: am, is e are",
    "Be pode significar ser ou estar; o contexto mostra a ideia. A forma varia com o sujeito: I am; you, we e they are; he, she e it is. Não misture be com do/does na mesma pergunta simples.",
    "I am hungry. / She is a teacher. / We are at home. / Are they ready?",
    [["I am hungry.", "Eu estou com fome.", "estado"], ["She is a teacher.", "Ela é professora.", "identidade ou profissão"], ["We are in the kitchen.", "Nós estamos na cozinha.", "localização"]],
    "Escreva uma frase com am, uma com is e uma com are. Use situações reais ou fictícias, sem dados pessoais.",
    ["hungry", "I", "am"],
    "I am hungry.",
    "No Pareto, recupere am, is, are, hungry, teacher e kitchen; escolha a forma de be pelo sujeito antes de falar.",
  ),
  lesson(
    "Be no passado: was e were",
    "No passado, be muda para was com I, he, she e it; use were com you, we e they. Essas formas contam como alguém ou algo estava em um momento anterior.",
    "I was at home. / She was tired. / We were at school. / Were they ready?",
    [["I was at your house yesterday.", "Eu estava na sua casa ontem.", "I + was"], ["She was tired after work.", "Ela estava cansada depois do trabalho.", "she + was"], ["They were at the office.", "Eles estavam no escritório.", "they + were"]],
    "Escreva três frases sobre um momento passado fictício: uma com was, uma com were e uma pergunta com Was ou Were.",
    ["was", "I", "at", "home", "yesterday"],
    "I was at home yesterday.",
    "No Pareto, recupere was, were, yesterday, home, office e tired; associe cada forma ao sujeito correto.",
  ),
  lesson(
    "Can: habilidade, possibilidade e permissão",
    "Can é um modal: ele não recebe -s com he, she ou it e vem antes do verbo-base. Use para habilidade, possibilidade simples ou pedido de permissão. A forma passada mais comum é could, mas ela não é futuro simples.",
    "I can swim. / She can cook. / Can I have some water? / Could you help me?",
    [["I can cook rice.", "Eu consigo cozinhar arroz.", "habilidade"], ["She can speak English.", "Ela consegue falar inglês.", "can não muda para she cans"], ["Can I have some water, please?", "Posso tomar um pouco de água, por favor?", "pedido de permissão"]],
    "Escreva uma habilidade com can, uma pergunta de permissão com Can I…? e um pedido educado com Could you…?.",
    ["can", "She", "speak", "English"],
    "She can speak English.",
    "No Pareto, recupere can, could, cook, speak, water e help; mantenha o verbo na forma-base depois do modal.",
  ),
  lesson(
    "Prática integrada: preparar uma mesa",
    "A prática final reúne quantidade, existência e ação. Primeiro diga o que há na mesa; depois pergunte o que falta; por fim, diga o que cada pessoa consegue fazer. Assim, as estruturas aparecem em uma cena, não em listas soltas.",
    "There is some soup. There are two cups. Is there any bread? I can bring it.",
    [["There is some soup and there are two cups on the table.", "Há sopa e duas xícaras sobre a mesa.", "is para sopa; are para cups"], ["Is there any bread? No, there is not.", "Há pão? Não, não há.", "pergunta e negativa"], ["I can bring the bread.", "Eu posso trazer o pão.", "can + verbo-base"]],
    "Escreva um diálogo de seis linhas em uma mesa: diga o que há, pergunte por um item, responda e ofereça ajuda com can.",
    ["can", "I", "bring", "the", "bread"],
    "I can bring the bread.",
    "No Pareto, recupere there is, there are, some, any, can e bread; descreva uma mesa e resolva uma falta com uma frase útil.",
  ),
];
