const lab = (
  title: string,
  explanation: string,
  languageFocus: string,
  target: string,
  native: string,
  writingPrompt: string,
  scrambled: string[],
  paretoPrompt: string,
) => ({
  section: "Laboratório de leitura e escrita",
  title,
  explanation,
  languageFocus,
  examples: [
    { target, native, note: "texto-modelo para compreender" },
    { target: `Listen and order: ${target}`, native: `Ouça, observe a ordem e compare: ${native}`, note: "ordem de ideias" },
    { target: `Write your version: ${target}`, native: `Escreva sua versão: ${native}`, note: "produção pessoal" },
  ],
  writingPrompt,
  scrambled,
  answer: target,
  paretoPrompt,
});

export const SEVENTH_BLOCK_LITERACY_LABS = [
  lab(
    "Ler uma rotina completa",
    "Leia primeiro a sequência inteira e só depois separe as ações. Um texto curto de rotina costuma avançar do início do dia para uma atividade e um resultado.",
    "Use first, then e after para reconhecer a sequência antes de tentar reorganizar as palavras.",
    "First, I make breakfast. Then, I study after work.",
    "Primeiro, eu preparo o café da manhã. Depois, estudo depois do trabalho.",
    "Escreva uma rotina de quatro frases e marque a palavra que inicia cada etapa.",
    ["First", "I", "make", "breakfast", "Then", "I", "study", "after", "work"],
    "No Pareto, recupere first, then, breakfast, study e work. Reorganize a rotina sem olhar para o modelo.",
  ),
  lab(
    "Localizar causa e resultado",
    "Em textos mais longos, procure a razão e a consequência. A razão explica por que algo acontece; o resultado mostra o que ocorreu depois.",
    "Because introduz razão; so introduz resultado. Não use os dois para a mesma relação de ideia.",
    "I missed the bus, so I called my colleague.",
    "Eu perdi o ônibus, então liguei para meu colega.",
    "Escreva duas situações: uma com because e outra com so. Explique em português qual é a razão em cada uma.",
    ["I", "missed", "the", "bus", "so", "I", "called", "my", "colleague"],
    "No Pareto, recupere miss, bus, call, colleague, because e so; produza causa e resultado em duas frases.",
  ),
  lab(
    "Ordenar um aviso de serviço",
    "Avisos claros apresentam ação, lugar e tempo. Ao ordenar as palavras, encontre primeiro o verbo de instrução e depois o local ou horário.",
    "Please suaviza a instrução; keep e bring indicam a ação solicitada.",
    "Please bring your ticket to the front desk.",
    "Por favor, leve seu bilhete ao balcão de atendimento.",
    "Escreva dois avisos úteis para uma estação, escola ou clínica.",
    ["Please", "bring", "your", "ticket", "to", "the", "front", "desk"],
    "No Pareto, recupere please, bring, ticket, desk e service; transforme um aviso em pedido educado.",
  ),
  lab(
    "Entender uma mensagem de viagem",
    "Uma mensagem de viagem reúne destino, horário e próxima ação. Leia todos os detalhes antes de decidir a ordem de uma frase mais extensa.",
    "Tomorrow, at seven e from the station respondem a quando e de onde a viagem começa.",
    "We leave from the station tomorrow at seven.",
    "Nós saímos da estação amanhã às sete.",
    "Escreva uma mensagem de viagem de quatro linhas com origem, destino, horário e transporte.",
    ["We", "leave", "from", "the", "station", "tomorrow", "at", "seven"],
    "No Pareto, recupere leave, station, tomorrow, seven e travel; monte um plano completo de deslocamento.",
  ),
  lab(
    "Responder a um colega de estudo",
    "Uma resposta de estudo confirma a mensagem recebida, informa a ação seguinte e pode acrescentar uma pergunta. Essa estrutura evita respostas vazias.",
    "I understand confirma; I will review anuncia ação; could you…? abre uma dúvida educada.",
    "I understand the task, and I will review it tonight.",
    "Eu entendo a tarefa e vou revisá-la hoje à noite.",
    "Escreva uma resposta de quatro linhas a um colega sobre uma tarefa de estudo.",
    ["I", "understand", "the", "task", "and", "I", "will", "review", "it", "tonight"],
    "No Pareto, recupere understand, task, review, tonight e will; responda a uma instrução com uma próxima ação.",
  ),
  lab(
    "Comparar duas escolhas reais",
    "Para comparar opções, apresente as duas, escolha uma característica e explique sua decisão. Evite mudar o critério no meio da frase.",
    "More convenient e less expensive permitem comparar soluções sem repetir toda a ideia.",
    "The train is more convenient, but the bus is less expensive.",
    "O trem é mais conveniente, mas o ônibus é menos caro.",
    "Compare duas formas de transporte, dois lugares ou duas opções de estudo em cinco frases.",
    ["The", "train", "is", "more", "convenient", "but", "the", "bus", "is", "less", "expensive"],
    "No Pareto, recupere train, bus, more, less, convenient e expensive; justifique uma escolha.",
  ),
  lab(
    "Reconstruir uma experiência passada",
    "Uma experiência passada fica clara quando contém tempo, ação e consequência. Organize primeiro o acontecimento principal e depois o que mudou.",
    "Yesterday e last week situam o texto; after that conduz a sequência seguinte.",
    "Yesterday, I visited my aunt after class.",
    "Ontem, visitei minha tia depois da aula.",
    "Escreva seis frases sobre uma experiência simples, mantendo os acontecimentos na ordem em que ocorreram.",
    ["Yesterday", "I", "visited", "my", "aunt", "after", "class"],
    "No Pareto, recupere yesterday, visit, aunt, class e after; conte um fato com começo e continuação.",
  ),
  lab(
    "Planejar uma ação futura",
    "Um plano futuro precisa dizer o que a pessoa fará, quando e, se necessário, por quê. Use uma frase por decisão antes de juntar ideias.",
    "Will anuncia uma decisão ou plano; next week oferece uma referência de tempo.",
    "Next week, I will practise English with my friend.",
    "Na próxima semana, vou praticar inglês com meu amigo.",
    "Escreva um plano de cinco frases para a próxima semana e inclua uma atividade de escuta, escrita e conversa.",
    ["Next", "week", "I", "will", "practise", "English", "with", "my", "friend"],
    "No Pareto, recupere next, week, will, practise, English e friend; transforme um desejo em plano.",
  ),
  lab(
    "Ler e responder a um problema",
    "Antes de responder a um problema, identifique o fato, a urgência e o pedido. A resposta útil reconhece a situação e oferece ou solicita uma ação.",
    "There is a problem apresenta o fato; I can help oferece apoio; could you…? pede uma ação.",
    "There is a problem with the reservation, but I can help you.",
    "Há um problema com a reserva, mas posso ajudar você.",
    "Escreva um diálogo de seis falas sobre resolver um problema em viagem, trabalho ou estudo.",
    ["There", "is", "a", "problem", "with", "the", "reservation", "but", "I", "can", "help", "you"],
    "No Pareto, recupere problem, reservation, help, can e but; responda a uma dificuldade com calma.",
  ),
  lab(
    "Unir quatro ideias em um texto",
    "Um texto maior não é uma frase enorme. Construa quatro frases: situação, detalhe, motivo e conclusão. Depois releia para verificar se cada frase leva à próxima.",
    "Use uma palavra de ligação por vez: first, because, so ou finally.",
    "I studied early because I had an important meeting.",
    "Eu estudei cedo porque tinha uma reunião importante.",
    "Produza um texto de seis frases sobre como você se prepara para uma atividade importante.",
    ["I", "studied", "early", "because", "I", "had", "an", "important", "meeting"],
    "No Pareto, recupere study, early, important, meeting e because; conecte quatro ideias com clareza.",
  ),
  lab(
    "Revisar a ordem de uma frase longa",
    "Ao revisar uma frase longa, encontre primeiro quem age e o verbo. Depois coloque objeto, lugar, tempo e motivo em blocos que não competem entre si.",
    "A ordem segura é sujeito + verbo + complemento + lugar/tempo + razão quando necessária.",
    "My sister works at the hospital on Mondays because she helps patients.",
    "Minha irmã trabalha no hospital às segundas-feiras porque ajuda pacientes.",
    "Crie três frases longas com pessoa, ação, lugar, tempo e motivo; depois destaque cada bloco com cores no caderno.",
    ["My", "sister", "works", "at", "the", "hospital", "on", "Mondays", "because", "she", "helps", "patients"],
    "No Pareto, recupere sister, work, hospital, Monday, help e because; reorganize a frase por blocos.",
  ),
  lab(
    "Escrever um pedido profissional",
    "Um pedido profissional começa com saudação, apresenta a necessidade, indica prazo ou contexto e agradece. A clareza importa mais do que palavras difíceis.",
    "Could you send…? faz um pedido educado; by Friday indica o prazo.",
    "Could you send the report by Friday, please?",
    "Você poderia enviar o relatório até sexta-feira, por favor?",
    "Escreva um e-mail de cinco linhas pedindo uma informação, documento ou confirmação de horário.",
    ["Could", "you", "send", "the", "report", "by", "Friday", "please"],
    "No Pareto, recupere could, send, report, Friday e please; pratique um pedido formal curto.",
  ),
  lab(
    "Defender uma escolha com exemplo",
    "Uma opinião forte apresenta posição, razão e exemplo. A frase de exemplo não repete a razão: ela mostra a ideia acontecendo em uma situação concreta.",
    "I think apresenta opinião; because oferece razão; for example torna a explicação concreta.",
    "I think daily practice helps because it builds confidence.",
    "Acho que a prática diária ajuda porque desenvolve confiança.",
    "Escreva uma opinião de seis frases sobre uma estratégia de estudo e inclua um exemplo próprio.",
    ["I", "think", "daily", "practice", "helps", "because", "it", "builds", "confidence"],
    "No Pareto, recupere think, daily, practice, help, because e confidence; defenda uma escolha com exemplo.",
  ),
  lab(
    "Ler instruções em sequência",
    "Instruções mais longas precisam ser lidas em ordem. Procure os verbos de ação e a palavra que marca o próximo passo antes de executar qualquer coisa.",
    "First, next e finally guiam a sequência; check confirma que a etapa foi concluída.",
    "First, open the form. Next, check the date and send it.",
    "Primeiro, abra o formulário. Depois, confira a data e envie-o.",
    "Escreva quatro instruções para concluir uma tarefa simples de estudo ou organização.",
    ["First", "open", "the", "form", "Next", "check", "the", "date", "and", "send", "it"],
    "No Pareto, recupere first, next, open, check, date e send; dê instruções em ordem correta.",
  ),
  lab(
    "Portfólio de autonomia",
    "O portfólio final reúne evidências reais: uma mensagem, uma descrição, uma opinião, uma pergunta e uma resposta. Releia cada produção e escolha o ponto que ainda quer revisar.",
    "A autonomia aparece quando você consegue escolher, produzir, revisar e pedir ajuda de maneira consciente.",
    "I can explain my idea and ask for help when I need it.",
    "Eu consigo explicar minha ideia e pedir ajuda quando preciso.",
    "Monte um portfólio de oito itens e escreva uma meta de revisão para os próximos trinta dias.",
    ["I", "can", "explain", "my", "idea", "and", "ask", "for", "help", "when", "I", "need", "it"],
    "No Pareto, recupere explain, idea, ask, help, need e review; escolha os termos que ainda precisam de repetição espaçada.",
  ),
];
