const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({
  section: "Comparativos e superlativos",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const FOURTEENTH_BLOCK_COMPARATIVES_SUPERLATIVES = [
  lesson("Comparativos curtos: -er + than", "Para muitos adjetivos curtos, use -er e depois than para comparar duas pessoas, objetos ou situações. Observe também mudanças de escrita: big vira bigger e happy vira happier.", "older than / taller than / slower than / bigger than / happier than", [["My aunt is older than my mother.", "Minha tia é mais velha que minha mãe.", "older + than"], ["You are taller than me.", "Você é mais alto que eu.", "comparação direta"], ["My dog is slower than your cat.", "Meu cachorro é mais lento que seu gato.", "adjetivo curto + -er"]], "Compare três pares do seu cotidiano com adjetivos curtos. Em cada frase, use than e diga em pt-BR quem ou o que está sendo comparado.", ["My", "dog", "is", "slower", "than", "your", "cat"], "My dog is slower than your cat.", "No Pareto, recupere older, taller, slower, bigger, happier e than; transforme o adjetivo curto na forma comparativa correta."),
  lesson("Comparativos longos: more + adjetivo + than", "Com muitos adjetivos de duas ou mais sílabas, use more antes do adjetivo e than depois dele. Não acrescente -er a essas formas longas.", "more intelligent than / more interesting than / more difficult than", [["Paul is more intelligent than Billy.", "Paul é mais inteligente que Billy.", "more + adjetivo longo"], ["This book is more interesting than that one.", "Este livro é mais interessante que aquele.", "comparação de objetos"], ["This test is more difficult than the one we had yesterday.", "Esta prova é mais difícil que a que tivemos ontem.", "contexto completo"]], "Escreva três comparações com more: uma pessoa, um livro/filme e uma tarefa. Confira se não usou more e -er juntos.", ["This", "book", "is", "more", "interesting", "than", "that", "one"], "This book is more interesting than that one.", "No Pareto, recupere more, intelligent, interesting, difficult, than e yesterday; separe adjetivos longos de formas curtas."),
  lesson("Superlativos curtos: the + -est", "Use the antes do superlativo para destacar um elemento de um grupo. Para muitos adjetivos curtos, acrescente -est: tall → tallest; big → biggest.", "the biggest / the tallest / the oldest / the fastest", [["Mexico City is one of the biggest cities on this continent.", "A Cidade do México é uma das maiores cidades deste continente.", "superlativo em grupo"], ["Mount Everest is the tallest mountain in the world.", "O Monte Everest é a montanha mais alta do mundo.", "the + tallest"], ["Sunday is the quietest day for me.", "Domingo é o dia mais tranquilo para mim.", "superlativo em contexto pessoal"]], "Escreva três superlativos com the: um lugar, uma pessoa de um grupo e um dia/objeto. Diga qual é o grupo de comparação.", ["Mount", "Everest", "is", "the", "tallest", "mountain"], "Mount Everest is the tallest mountain.", "No Pareto, recupere the, biggest, tallest, oldest, fastest e quietest; marque o grupo antes de criar o superlativo."),
  lesson("Superlativos longos e formas irregulares", "Com adjetivos longos, use the most + adjetivo. Algumas formas são irregulares e precisam ser aprendidas como conjunto: good → better → best; bad → worse → worst.", "the most intelligent / the most interesting / better than / the best / worse than / the worst", [["Kate is the most intelligent girl in the class.", "Kate é a aluna mais inteligente da turma.", "the most + adjetivo longo"], ["This is the best option for today.", "Esta é a melhor opção para hoje.", "good → best"], ["That was the worst day of the week.", "Aquele foi o pior dia da semana.", "bad → worst"]], "Crie uma frase com the most e duas com melhor/pior em inglês. Depois, escreva a sequência-base de good e bad sem traduzir palavra por palavra.", ["Kate", "is", "the", "most", "intelligent", "girl"], "Kate is the most intelligent girl.", "No Pareto, recupere most, best, worst, better, worse e intelligent; reconheça forma longa e irregular antes de responder."),
  lesson("Prática contextual: clima, lugares e matérias", "A prática do original usa lacunas para escolher comparativos e superlativos. Nesta reconstrução, cada resposta exige observar o grupo, o tipo de adjetivo e a relação de comparação.", "warmer than / the hottest / more interesting than / the most interesting", [["The weather is warm in Cuernavaca, but it is warmer in Acapulco.", "O tempo é quente em Cuernavaca, mas é mais quente em Acapulco.", "comparativo curto"], ["The Sonora Desert is one of the hottest places in Mexico.", "O Deserto de Sonora é um dos lugares mais quentes do México.", "superlativo em grupo"], ["Literature is the most interesting subject of all for me.", "Para mim, literatura é a matéria mais interessante de todas.", "superlativo longo"]], "Complete quatro lacunas próprias: duas comparações e dois superlativos. Explique em pt-BR por que escolheu -er, more, -est ou most.", ["Literature", "is", "the", "most", "interesting", "subject"], "Literature is the most interesting subject.", "No Pareto, recupere warmer, hottest, more interesting, most interesting, weather e subject; justifique a escolha de cada forma."),
];
