const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({
  section: "Saudações, despedidas e calendário",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const FIFTEENTH_BLOCK_GREETINGS_CALENDAR = [
  lesson("Saudações: registro e momento do dia", "O original organiza saudações por cordialidade e horário. Use hi e hello em situações informais; use good morning, good afternoon e good evening conforme o período. A referência de pronúncia é o áudio nativo, não uma fonetização hispanizada.", "Hi / Hello / Nice to meet you / Pleased to meet you / Good morning / Good afternoon / Good evening", [["Hi, Ana. How are you?", "Oi, Ana. Como você está?", "informal"], ["Nice to meet you, Mr. Brown.", "Prazer em conhecê-lo, Sr. Brown.", "primeiro encontro cordial"], ["Good afternoon, everyone.", "Boa tarde, pessoal.", "período do dia"]], "Escreva três saudações: uma informal, uma para primeiro encontro e uma para uma turma à tarde. Marque o registro em pt-BR.", ["Nice", "to", "meet", "you"], "Nice to meet you.", "No Pareto, recupere hi, hello, nice to meet you, good morning, afternoon e evening; escolha pelo contexto de encontro."),
  lesson("Despedidas: informalidade e continuidade", "Despedidas também mudam de acordo com a situação. See you e see you later são informais; bye é curto e cotidiano; goodbye pode ser cordial. A forma de encontro não deve ser usada automaticamente como despedida sem contexto.", "See you / See you later / Bye / Goodbye / Have a nice day", [["See you later, Maria.", "Até mais, Maria.", "informal"], ["Bye! Have a nice day.", "Tchau! Tenha um bom dia.", "despedida cotidiana"], ["Goodbye, Mr. Brown.", "Adeus/Até logo, Sr. Brown.", "cordial"]], "Escreva um diálogo de quatro linhas: saudação, resposta, despedida e resposta. Use um registro coerente do início ao fim.", ["See", "you", "later"], "See you later.", "No Pareto, recupere see you, later, bye, goodbye, day e have; associe cada despedida ao grau de formalidade."),
  lesson("Dias da semana e fim de semana", "Os dias e meses em inglês começam com letra maiúscula. Use on com dias específicos e at/on no período do fim de semana conforme a variedade e o contexto; aqui o foco é reconhecer os nomes e usá-los em frases simples.", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, weekend", [["I have to work on Saturday.", "Eu tenho de trabalhar no sábado.", "on + dia"], ["He will go to my house on Sunday morning.", "Ele irá à minha casa na manhã de domingo.", "dia + período"], ["Have a nice weekend.", "Tenha um bom fim de semana.", "expressão útil"]], "Escreva sua rotina de três dias da semana. Inclua uma atividade e um período do dia em cada frase.", ["I", "have", "to", "work", "on", "Saturday"], "I have to work on Saturday.", "No Pareto, recupere Monday, Friday, Saturday, Sunday, weekend e work; conecte dias a ações reais."),
  lesson("Meses do ano em contexto", "Os meses também usam inicial maiúscula e normalmente aparecem com in: in August, in March. A lista do original é mantida em ordem, sempre ligada a uma frase possível e não só à memorização isolada.", "January through December / in August / in March / in December", [["My son was born in August.", "Meu filho nasceu em agosto.", "in + mês"], ["She will get married in March.", "Ela se casará em março.", "plano em mês"], ["December is a very cold month.", "Dezembro é um mês muito frio.", "mês em descrição"]], "Escreva três frases usando meses: aniversário, evento futuro e clima. Confira as letras maiúsculas antes de responder.", ["My", "son", "was", "born", "in", "August"], "My son was born in August.", "No Pareto, recupere January, March, August, December, month e born; use in + mês nas frases."),
  lesson("Estações do ano e plano de viagem", "As estações do original são spring, summer, fall/autumn e winter. Use a estação para falar de clima e planos; a frase completa vale mais do que decorar uma lista.", "spring / summer / fall or autumn / winter / seasons of the year", [["This is a very hot summer.", "Este é um verão muito quente.", "estação + clima"], ["I will go to Mexico next winter.", "Irei ao México no próximo inverno.", "plano futuro"], ["Spring is my favorite season.", "A primavera é minha estação favorita.", "preferência pessoal"]], "Escreva um plano para uma estação e uma descrição de clima para outra. Inclua uma razão para sua preferência.", ["I", "will", "go", "to", "Mexico", "next", "winter"], "I will go to Mexico next winter.", "No Pareto, recupere spring, summer, fall, winter, season e next; ligue estações a clima e planos pessoais."),
];
