const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({
  section: "Negações, perfect e pronomes reflexivos",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const TENTH_BLOCK_NEGATIONS_AND_SELF = [
  lesson("Negação no presente: forma cheia e contraída", "Com be, coloque not depois de am/is/are. Com outros verbos no presente simples, use do not ou does not e mantenha o verbo-base. Contrações encurtam a fala, mas a forma cheia também precisa ser reconhecida.", "He is not my brother. / You are not a doctor. / We do not want eggs. / She doesn't visit her family.", [["He is not my brother.", "Ele não é meu irmão.", "be + not"], ["We do not want eggs for breakfast.", "Nós não queremos ovos no café da manhã.", "do not + verbo-base"], ["She doesn't visit her family.", "Ela não visita a família dela.", "contração com does"]], "Escreva duas negativas completas e depois reescreva uma delas com contração.", ["doesn't", "She", "visit", "her", "family"], "She doesn't visit her family.", "No Pareto, recupere not, isn't, aren't, don't, doesn't e visit; escolha be ou do/does antes de negar."),
  lesson("Negação no passado: was, were e did", "Use was not e were not com be no passado. Para outros verbos, use did not + verbo-base. Não use did com a forma passada do verbo principal.", "I wasn't there. / You weren't at home. / You did not take the books to school.", [["I wasn't there when they arrived.", "Eu não estava lá quando eles chegaram.", "was not contraído"], ["You weren't at home on Sunday.", "Você não estava em casa no domingo.", "were not contraído"], ["You didn't take the books to school.", "Você não levou os livros para a escola.", "did + take, não took"]], "Escreva uma negativa no passado com be e outra com did not. Circule o verbo-base depois de did.", ["didn't", "You", "take", "the", "books"], "You didn't take the books.", "No Pareto, recupere wasn't, weren't, didn't, arrive, take e school; separe be no passado de ação passada."),
  lesson("Will not e would not: sentido em contexto", "Will not indica futuro ou decisão negativa; a contração é won't. Would not pode indicar recusa, hipótese ou condição; a contração é wouldn't. Não trate would como simples futuro.", "She won't drive my car. / I wouldn't eat that soup. / I will not be late.", [["She won't drive my car.", "Ela não dirigirá meu carro.", "futuro/decisão negativa"], ["I wouldn't eat that soup.", "Eu não comeria essa sopa.", "hipótese ou recusa"], ["I will not be late.", "Eu não vou me atrasar.", "forma cheia"]], "Escreva uma negativa com won't e outra com wouldn't. Em português, explique a intenção de cada uma.", ["wouldn't", "I", "eat", "that", "soup"], "I wouldn't eat that soup.", "No Pareto, recupere will, won't, would, wouldn't, drive e eat; compare futuro com hipótese."),
  lesson("Perfect negativo: have/has/had + particípio", "Em tempos perfeitos, not fica depois de have, has ou had; o verbo seguinte precisa estar no particípio. A correção essencial é had not climbed, não had not climb.", "I haven't seen that tree. / He hasn't studied for the exam. / We hadn't climbed the mountain.", [["I haven't seen that tree.", "Eu não vi / não tenho visto aquela árvore.", "have + particípio"], ["He hasn't studied for the exam.", "Ele não estudou para a prova.", "has + particípio"], ["We hadn't climbed the mountain.", "Nós não tínhamos escalado a montanha.", "had + particípio corrigido"]], "Escreva uma frase com haven't, outra com hasn't e uma com hadn't. Confira se o verbo final está no particípio.", ["hadn't", "We", "climbed", "the", "mountain"], "We hadn't climbed the mountain.", "No Pareto, recupere haven't, hasn't, hadn't, seen, studied e climbed; identifique o auxiliar e o particípio."),
  lesson("Pronomes em -self: reflexo, sozinho e ênfase", "Myself, yourself, himself, herself, itself, ourselves, yourselves e themselves têm usos diferentes. Use reflexivo quando a ação volta ao sujeito; use by + self para sem ajuda; use o pronome após o nome para dar ênfase.", "I see myself in the mirror. / He painted the house by himself. / The king himself visited the hospital.", [["I see myself in the mirror.", "Eu me vejo no espelho.", "reflexivo"], ["She did her homework by herself.", "Ela fez a lição sozinha.", "sem ajuda"], ["The teacher herself answered the question.", "A própria professora respondeu à pergunta.", "ênfase"]], "Escreva uma frase para cada uso: reflexivo, by + self e ênfase. Identifique a função em português.", ["herself", "The", "teacher", "answered", "the", "question"], "The teacher herself answered the question.", "No Pareto, recupere myself, herself, themselves, by e mirror; classifique cada uso antes de formar uma frase."),
];
