const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({ section: "Phrasal verbs e idioms", title, explanation, languageFocus, examples: examples.map(([target, native, note]) => ({ target, native, note })), writingPrompt, scrambled, answer, paretoPrompt });

export const SIXTEENTH_BLOCK_PHRASALS_IDIOMS = [
  lesson("Expressões de tempo e comentário", "O original começa com expressões fixas. Elas devem ser aprendidas no contexto, pois não se traduzem palavra por palavra.", "all of a sudden / as usual / at first / at last / at once / by the way", [["All of a sudden, the dancers arrived.", "De repente, os dançarinos chegaram.", "mudança inesperada"], ["At first, I worked in the library.", "No início, trabalhei na biblioteca.", "início de uma sequência"], ["By the way, have you seen Celia?", "A propósito, você viu a Celia?", "comentário adicional"]], "Crie três frases, cada uma com uma expressão fixa; explique em pt-BR a função de cada expressão.", ["By", "the", "way", "have", "you", "seen", "Celia"], "By the way, have you seen Celia?", "No Pareto, recupere all of a sudden, at first, at last, at once e by the way; escolha a expressão pela situação."),
  lesson("Call e figure out", "Phrasal verbs mudam de sentido com a partícula. Call up é telefonar; call on é visitar/chamar alguém; call off é cancelar; figure out é descobrir ou entender após pensar.", "call up / call on / call off / figure out / for good", [["Call up the travel agency.", "Ligue para a agência de viagens.", "telefonar"], ["We have to call off the meeting.", "Temos de cancelar a reunião.", "cancelar"], ["I finally figured out why he left.", "Finalmente entendi por que ele saiu.", "descobrir/entender"]], "Escreva uma frase para call off e outra para figure out. Não traduza call ou figure isoladamente.", ["We", "have", "to", "call", "off", "the", "meeting"], "We have to call off the meeting.", "No Pareto, recupere call up, call off, figure out, meeting e finally; diga o sentido completo de cada combinação."),
  lesson("Get: movimento, estado e contato", "O grupo get muda de sentido conforme a partícula e o complemento. O contexto decide se fala de entrar, sair, chegar, recuperar-se ou entrar em contato.", "get on / get off / get up / get along / get over / get in touch with / get rid of", [["I get on the bus at Hidalgo Street.", "Eu pego o ônibus na Rua Hidalgo.", "embarcar"], ["She got over her cold and now she is feeling well.", "Ela se recuperou do resfriado e agora está bem.", "recuperar-se"], ["We need to get in touch with the manager.", "Precisamos entrar em contato com o gerente.", "contato"]], "Use três itens com get em frases de transporte, saúde e comunicação. Indique o sentido completo em pt-BR.", ["We", "need", "to", "get", "in", "touch", "with", "the", "manager"], "We need to get in touch with the manager.", "No Pareto, recupere get on, get off, get over, get in touch with, manager e bus; associe cada um a um contexto."),
  lesson("Continuidade, omissão e descanso", "O terceiro conjunto do original combina expressões de conselho, continuidade, omissão e descanso. A construção inteira é a unidade de sentido.", "had better / hang up / have time off / keep on / leave out / lie down / little by little", [["You had better speak to your boss.", "É melhor você falar com seu chefe.", "conselho forte"], ["They keep on working until six.", "Eles continuam trabalhando até as seis.", "continuidade"], ["Do not leave out any detail.", "Não omita nenhum detalhe.", "não deixar de fora"]], "Transforme uma situação em conselho com had better e escreva uma frase com keep on ou leave out.", ["Do", "not", "leave", "out", "any", "detail"], "Do not leave out any detail.", "No Pareto, recupere had better, keep on, leave out, lie down e little by little; reconheça conselho, ação contínua e omissão."),
  lesson("Look: observar, procurar, cuidar e revisar", "Look ganha sentidos diferentes com cada partícula. Aprenda a combinação completa e a situação em que ela aparece.", "look at / look for / look out / look over", [["Look at that train.", "Olhe para aquele trem.", "observar"], ["I have to look for a new apartment.", "Tenho de procurar um apartamento novo.", "buscar"], ["Look over the contract before you sign it.", "Revise o contrato antes de assiná-lo.", "examinar/revisar"]], "Escreva uma frase com look for e outra com look over. Explique em pt-BR por que as partículas mudam o sentido.", ["Look", "over", "the", "contract", "before", "you", "sign", "it"], "Look over the contract before you sign it.", "No Pareto, recupere look at, look for, look out, look over, contract e sign; associe ação e contexto."),
];
