const lesson = (
  title: string,
  explanation: string,
  languageFocus: string,
  examples: Array<[string, string, string]>,
  writingPrompt: string,
  scrambled: string[],
  answer: string,
  paretoPrompt: string,
) => ({
  section: "Auxiliares, modais e tempos em contexto",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const NINTH_BLOCK_AUXILIARIES_AND_TENSES = [
  lesson(
    "Do, does e did: auxiliar não substitui o verbo",
    "Do e does formam perguntas e negativas no presente; did faz o mesmo no passado. Depois do auxiliar, o verbo fica na forma-base. Afirmativas simples não recebem do, does ou did.",
    "Do you speak English? / He does not understand Spanish. / Did she study yesterday?",
    [["Do you speak English?", "Você fala inglês?", "pergunta no presente"], ["He does not understand Spanish.", "Ele não entende espanhol.", "does + verbo-base"], ["Did she study yesterday?", "Ela estudou ontem?", "did + verbo-base"]],
    "Escreva uma pergunta com do, uma negativa com does e uma pergunta passada com did. Confira se o verbo ficou na forma-base.",
    ["Did", "she", "study", "yesterday"],
    "Did she study yesterday?",
    "No Pareto, recupere do, does, did, speak, understand e study; escolha o auxiliar pelo tempo e sujeito.",
  ),
  lesson(
    "Will e would: futuro não é a única função",
    "Will pode apresentar decisão, previsão ou futuro. Would não é futuro simples: aparece em hipótese, condicional e pedidos educados. Ambos vêm antes do verbo-base.",
    "I will see you at school. / She will be in the office. / Would you help me, please?",
    [["I will see you at school.", "Eu verei você na escola.", "futuro ou decisão"], ["She will be in the office.", "Ela estará no escritório.", "will + be"], ["Would you help me, please?", "Você poderia me ajudar, por favor?", "pedido educado"]],
    "Escreva uma decisão futura com will e um pedido educado com would. Não chame would de futuro simples.",
    ["will", "I", "see", "you", "tomorrow"],
    "I will see you tomorrow.",
    "No Pareto, recupere will, would, see, help, tomorrow e please; separe decisão futura de pedido educado.",
  ),
  lesson(
    "Can, could, may, might e must: intenções diferentes",
    "Can e could falam de habilidade, permissão ou possibilidade conforme o contexto. May e might expressam possibilidade, e may também pode ser uma permissão mais formal. Must marca obrigação forte.",
    "She can drive. / Could you help? / It might rain. / May I ask a question? / We must study.",
    [["She can drive to work.", "Ela consegue dirigir para o trabalho.", "habilidade"], ["It might rain later.", "Pode chover mais tarde.", "possibilidade"], ["We must study for the test.", "Nós devemos estudar para a prova.", "obrigação"]],
    "Crie uma frase de habilidade, uma de possibilidade e uma de obrigação. Depois de cada modal, mantenha o verbo-base.",
    ["must", "We", "study", "for", "the", "test"],
    "We must study for the test.",
    "No Pareto, recupere can, could, may, might, must e study; associe cada modal à intenção correta.",
  ),
  lesson(
    "Have, has e had: posse, obrigação e experiência",
    "Have pode indicar posse, obrigação com have to ou experiência em tempos perfeitos. A função depende da estrutura: I have a book; I have to learn; I have visited. Não misture as três leituras.",
    "I have a book. / She has to clean her room. / They have seen three cats. / He had finished the job.",
    [["I have a book.", "Eu tenho um livro.", "posse"], ["She has to clean her room.", "Ela tem de limpar o quarto.", "obrigação"], ["I have visited my uncle.", "Eu visitei meu tio / já visitei meu tio.", "experiência com present perfect"]],
    "Escreva uma frase de posse, uma com have to/has to e uma com have/has + particípio. Marque a função de cada have.",
    ["have", "I", "visited", "my", "uncle"],
    "I have visited my uncle.",
    "No Pareto, recupere have, has, had, book, clean e visited; classifique posse, obrigação e experiência antes de responder.",
  ),
  lesson(
    "Be + -ing: ação em andamento",
    "O presente contínuo usa am/is/are + verbo com -ing; o passado contínuo usa was/were + -ing. Ele destaca uma ação em progresso em um momento, não uma regra geral.",
    "The girl is playing in the backyard. / I was listening to music. / They were waiting for the bus.",
    [["The girl is playing in the backyard.", "A menina está brincando no quintal.", "ação em andamento agora"], ["I was listening to music.", "Eu estava ouvindo música.", "ação em andamento no passado"], ["They were waiting for the bus.", "Eles estavam esperando o ônibus.", "wait for + transporte"]],
    "Escreva uma ação em andamento agora e outra no passado. Use be + -ing e mantenha for depois de wait quando houver objeto esperado.",
    ["were", "They", "waiting", "for", "the", "bus"],
    "They were waiting for the bus.",
    "No Pareto, recupere is, were, playing, listening, waiting e bus; escolha presente ou passado contínuo pelo momento descrito.",
  ),
  lesson(
    "Prática integrada: explicar um plano e uma ação",
    "A prática reúne auxiliares e tempos em um diálogo curto. Primeiro informe um plano, depois peça ajuda ou permissão e descreva uma ação em andamento. Cada estrutura tem uma função própria.",
    "I will study tonight. Could you help me? I am reviewing the lesson now.",
    [["I will study tonight.", "Eu estudarei hoje à noite.", "plano"], ["Could you help me with this exercise?", "Você poderia me ajudar com este exercício?", "pedido"], ["I am reviewing the lesson now.", "Estou revisando a lição agora.", "ação em andamento"]],
    "Escreva um diálogo de seis linhas com um plano usando will, um pedido com could e uma ação em andamento com be + -ing.",
    ["am", "I", "reviewing", "the", "lesson", "now"],
    "I am reviewing the lesson now.",
    "No Pareto, recupere will, could, am, study, help, review e now; transforme cada palavra em uma fala útil de diálogo.",
  ),
];
