const lesson = (
  title: string,
  explanation: string,
  languageFocus: string,
  examples: Array<[string, string, string]>,
  writingPrompt: string,
  scrambled: string[],
  answer: string,
  paretoPrompt: string,
) => ({
  section: "Advérbios, produção guiada e viagens",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const ELEVENTH_BLOCK_ADVERBS_AND_TRAVEL = [
  lesson(
    "Advérbios e quantificadores em pares úteis",
    "Este trecho reúne advérbios e quantificadores para ampliar a montagem de frases. A chave é distinguir quantidade, tempo, lugar e intensidade sem trocar many por much nem talvez por certeza.",
    "How many / too much / too many / somewhere / anywhere / nowhere / tomorrow / always / already",
    [
      ["How many books do you have?", "Quantos livros você tem?", "how many para contáveis"],
      ["There is too much sugar in the coffee.", "Há açúcar demais no café.", "too much para incontáveis"],
      ["She is already here.", "Ela já está aqui.", "already em contexto real"],
    ],
    "Escreva quatro frases: uma com quantidade contável, uma com incontável, uma com lugar e uma com tempo. Explique em português por que escolheu cada advérbio.",
    ["She", "is", "already", "here"],
    "She is already here.",
    "No Pareto, recupere how many, too much, too many, somewhere, tomorrow e already; separe quantidade, lugar e tempo antes de responder.",
  ),
  lesson(
    "Frases-modelo com advérbios em contexto",
    "O original passa da lista para frases completas. A reconstrução mantém essa transição, mas corrige naturalidade e comparação. Em inglês natural, diz-se as well as ou as well as her grandmother, não as good as para cozinhar nesse exemplo.",
    "Are you sure? / He is my only friend. / How much is the dog? / I will go to the office while you clean the house.",
    [
      ["Are you sure?", "Você tem certeza?", "advérbio/adjetivo de certeza em pergunta"],
      ["My brother is somewhere in Mexico.", "Meu irmão está em algum lugar do México.", "somewhere com lugar indefinido"],
      ["My mother cooks as well as my grandmother.", "Minha mãe cozinha tão bem quanto a minha avó.", "comparação corrigida e natural"],
    ],
    "Reescreva três frases-modelo do bloco: uma com certeza, uma com lugar indefinido e uma com comparação natural. Leia em voz alta com apoio do áudio nativo.",
    ["My", "brother", "is", "somewhere", "in", "Mexico"],
    "My brother is somewhere in Mexico.",
    "No Pareto, recupere sure, only, somewhere, yesterday, while e well; monte frases completas com posição correta dos advérbios.",
  ),
  lesson(
    "Produção guiada a partir do que se vê",
    "Depois das frases-modelo, o original convida o aluno a olhar ao redor e descrever a cena. A reconstrução preserva esse impulso de produção livre, mas com orientação direta em pt-BR para tempo, lugar e frequência.",
    "Now I can drive my car. / Pete goes to church often. / She was late again. / You can wait outside.",
    [
      ["Now I can drive my car.", "Agora eu consigo dirigir meu carro.", "now + can em contexto pessoal"],
      ["Pete goes to church often.", "Pete vai à igreja com frequência.", "often com hábito"],
      ["You can wait outside.", "Você pode esperar do lado de fora.", "outside como lugar"],
    ],
    "Observe um objeto, uma pessoa e uma ação ao seu redor. Escreva três frases próprias usando um advérbio de tempo, um de frequência e um de lugar.",
    ["Pete", "goes", "to", "church", "often"],
    "Pete goes to church often.",
    "No Pareto, recupere now, often, again, outside, can e drive; produza frases próprias ligadas ao que você vê.",
  ),
  lesson(
    "Viagens: transporte e deslocamento",
    "O capítulo seguinte reúne vocabulário de viagem. A reconstrução preserva o inventário principal e corrige grafias candidatas, sem trocar o núcleo lexical do original.",
    "airport / seat / airplane / ship / cabin / bus / captain / road / driver / seat belts / baggage / train station / passport / departure",
    [
      ["We arrived at the airport early.", "Nós chegamos cedo ao aeroporto.", "airport em contexto real"],
      ["Please fasten your seat belt.", "Por favor, aperte o cinto de segurança.", "seat belt corrigido e contextualizado"],
      ["The driver took the baggage to the bus.", "O motorista levou a bagagem para o ônibus.", "driver + baggage em deslocamento"],
    ],
    "Escreva uma microcena de viagem com pelo menos cinco palavras do bloco: meio de transporte, documento, bagagem e um horário ou advérbio.",
    ["We", "arrived", "at", "the", "airport", "early"],
    "We arrived at the airport early.",
    "No Pareto, recupere airport, airplane, bus, baggage, passport e departure; ligue cada palavra a uma ação real de viagem.",
  ),
  lesson(
    "Lugares para visitar e roteiro simples",
    "O original fecha o trecho com lugares para visitar. A reconstrução mantém o catálogo principal, corrige coffe shop para coffee shop e usa um pequeno roteiro para transformar lista em fala útil.",
    "aquarium / coffee shop / museum / park / beach / theatre / zoo / restaurant",
    [
      ["We can visit the aquarium in the morning.", "Podemos visitar o aquário pela manhã.", "lugar + tempo"],
      ["After that, we can have lunch at the restaurant.", "Depois disso, podemos almoçar no restaurante.", "sequência de roteiro"],
      ["In the evening, they want to go to the theatre.", "À noite, eles querem ir ao teatro.", "lugar + período do dia"],
    ],
    "Monte um roteiro simples de passeio com três paradas usando lugares do bloco e conectores de tempo como first, after that e in the evening.",
    ["We", "can", "visit", "the", "aquarium", "first"],
    "We can visit the aquarium first.",
    "No Pareto, recupere aquarium, coffee shop, museum, beach, theatre e restaurant; transforme a lista em um plano de passeio completo.",
  ),
];
