const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({ section: "Corpo humano, campo e planeta", title, explanation, languageFocus, examples: examples.map(([target, native, note]) => ({ target, native, note })), writingPrompt, scrambled, answer, paretoPrompt });

export const SEVENTEENTH_BLOCK_BODY_FIELD_PLANET = [
  lesson("Corpo humano: rosto, tronco e membros", "O original usa uma lista anatômica ilustrada. A reconstrução organiza o vocabulário por regiões do corpo e usa frases simples para transformar a lista em observação real.", "head, hair, eyes, ears, mouth, neck, shoulders, chest, back, arms, hands, fingers, legs", [["Her hair is long and her eyes are brown.", "O cabelo dela é longo e os olhos dela são castanhos.", "rosto"], ["My shoulders and back are tired.", "Meus ombros e minhas costas estão cansados.", "tronco"], ["He raised his hand and pointed with one finger.", "Ele levantou a mão e apontou com um dedo.", "membro"]], "Descreva uma pessoa em três frases respeitosas, usando vocabulário do rosto, tronco e membros.", ["He", "raised", "his", "hand"], "He raised his hand.", "No Pareto, recupere head, eyes, mouth, shoulders, hands e fingers; ligue cada palavra à região do corpo."),
  lesson("Singular e plural no corpo", "Algumas partes do corpo têm plural irregular. Use tooth/teeth e foot/feet como pares completos, sem tentar formar o plural apenas com -s.", "tooth → teeth / foot → feet / eye → eyes / knee → knees", [["I have one tooth that hurts.", "Tenho um dente que dói.", "singular"], ["Children have twenty baby teeth.", "Crianças têm vinte dentes de leite.", "plural irregular"], ["Her feet are cold after the rain.", "Os pés dela estão frios depois da chuva.", "foot → feet"]], "Escreva quatro pares singular/plural e crie duas frases: uma com teeth e outra com feet.", ["Her", "feet", "are", "cold"], "Her feet are cold.", "No Pareto, recupere tooth, teeth, foot, feet, knee e blood; marque quais formas têm plural irregular."),
  lesson("O campo: pessoas, lugares e cultivo", "O inventário do campo do original reúne pessoas, locais, plantas e ações. A prática agrupa o vocabulário para que o aluno use as palavras em cenário, não só em lista.", "farm, farmer, field, garden, orchard, crop, grain, seed, cultivate, harvest", [["The farmer cultivates corn on the farm.", "O fazendeiro cultiva milho na fazenda.", "pessoa + ação + lugar"], ["They planted seeds in the garden.", "Eles plantaram sementes no jardim.", "cultivo"], ["The harvest was good this year.", "A colheita foi boa este ano.", "resultado do cultivo"]], "Descreva uma cena no campo usando agricultor, lugar, planta e ação. Depois, troque apenas o tipo de cultivo.", ["The", "farmer", "cultivates", "corn"], "The farmer cultivates corn.", "No Pareto, recupere farm, farmer, seed, crop, harvest e cultivate; monte uma cadeia pessoa–ação–resultado."),
  lesson("Paisagem e clima rural", "O original também inclui relevo, água, clima e ferramentas. Organize as palavras por paisagem e fenômeno natural para criar descrições completas.", "hill, mountain, valley, river, lake, rain, snow, cloud, wind, ground, shovel", [["The river runs through the valley.", "O rio passa pelo vale.", "paisagem"], ["Snow covered the mountain.", "A neve cobriu a montanha.", "clima e relevo"], ["The wind moved the clouds over the field.", "O vento moveu as nuvens sobre o campo.", "fenômeno natural"]], "Escreva uma descrição de cinco linhas de uma paisagem rural, incluindo relevo, água e clima.", ["The", "river", "runs", "through", "the", "valley"], "The river runs through the valley.", "No Pareto, recupere river, mountain, valley, rain, snow e wind; combine natureza e ação em frases observáveis."),
  lesson("Planeta Terra: geografia e fenômenos", "A última lista do capítulo amplia o cenário para o planeta. O foco é diferenciar geografia, astros, clima e fenômenos intensos com frases seguras e contextuais.", "Earth, sky, ocean, jungle, North, South, East, West, Moon, Mars, thunder, lightning, earthquake, tornado", [["The Moon is visible in the night sky.", "A Lua é visível no céu noturno.", "astro e céu"], ["The ocean is west of the city.", "O oceano fica a oeste da cidade.", "direção"], ["Lightning and thunder often come during a storm.", "Relâmpago e trovão geralmente ocorrem durante uma tempestade.", "fenômeno natural"]], "Crie quatro frases: uma de geografia, uma de direção, uma de astro e uma de clima. Use linguagem informativa, sem dramatizar riscos.", ["The", "Moon", "is", "visible", "in", "the", "night", "sky"], "The Moon is visible in the night sky.", "No Pareto, recupere Earth, ocean, Moon, North, lightning e thunder; separe lugar, direção, astro e fenômeno."),
];
