const lesson = (title: string, explanation: string, languageFocus: string, examples: Array<[string, string, string]>, writingPrompt: string, scrambled: string[], answer: string, paretoPrompt: string) => ({
  section: "Adjetivos qualificativos e cores",
  title,
  explanation,
  languageFocus,
  examples: examples.map(([target, native, note]) => ({ target, native, note })),
  writingPrompt,
  scrambled,
  answer,
  paretoPrompt,
});

export const THIRTEENTH_BLOCK_ADJECTIVES_AND_COLORS = [
  lesson("Posição e forma dos adjetivos", "Em inglês, o adjetivo qualificativo normalmente vem antes do substantivo: a tall tree. Ele não muda para masculino, feminino, singular ou plural. Essa é uma diferença estrutural importante em relação ao português.", "a tall tree / a tall man / tall trees / a beautiful house", [["Horacio is a tall man.", "Horacio é um homem alto.", "adjetivo antes do substantivo"], ["They live in a beautiful house.", "Eles moram em uma casa bonita.", "forma invariável"], ["We saw tall trees.", "Nós vimos árvores altas.", "plural sem mudança no adjetivo"]], "Escreva três grupos nominais: pessoa, objeto e lugar. Em cada um, coloque o adjetivo antes do substantivo e compare a ordem com o português.", ["a", "tall", "man", "is", "Horacio"], "Horacio is a tall man.", "No Pareto, recupere tall, beautiful, small, old, young e house; monte grupos com adjetivo antes do nome."),
  lesson("Adjetivos de aparência, tamanho e qualidade", "O inventário do original reúne muitos qualificativos. Nesta folha, organize-os por função para que o aluno não memorize apenas uma lista: aparência, tamanho, qualidade e estado.", "pretty, ugly, wide, narrow, small, large, clean, dirty, difficult, easy", [["It is a wide road.", "É uma estrada larga.", "tamanho/largura"], ["This is a difficult exercise.", "Este é um exercício difícil.", "qualidade da tarefa"], ["The room is clean and quiet.", "O quarto está limpo e silencioso.", "estado do lugar"]], "Descreva uma pessoa, um objeto e um ambiente usando dois adjetivos em cada frase. Evite repetir good para tudo: escolha a qualidade específica.", ["a", "difficult", "exercise", "is", "This"], "This is a difficult exercise.", "No Pareto, recupere wide, narrow, clean, dirty, difficult e easy; agrupe por função antes de formar frases."),
  lesson("Adjetivos de caráter, emoção e condição", "Alguns adjetivos descrevem caráter, emoção ou condição física. Use-os com cuidado e sempre em contexto, sem transformar uma característica passageira em rótulo permanente de uma pessoa.", "honest, kind, careful, happy, sad, sick, healthy, courageous, loyal, wise", [["My father is an honest man.", "Meu pai é um homem honesto.", "caráter"], ["The doctor said I was a healthy young man.", "O médico disse que eu era um jovem saudável.", "condição e idade"], ["My godfather is a kind person.", "Meu padrinho é uma pessoa gentil.", "kind em contexto natural"]], "Escreva três frases respeitosas: uma sobre caráter, uma sobre emoção e uma sobre condição. Diga em pt-BR qual é a categoria de cada adjetivo.", ["an", "honest", "man", "is", "My", "father"], "My father is an honest man.", "No Pareto, recupere honest, kind, healthy, happy, sad e loyal; classifique caráter, emoção ou condição antes de responder."),
  lesson("Frases-modelo: intensificadores e combinação", "O original passa da lista para frases curtas. A reconstrução preserva esse passo, incluindo very como intensificador e combinações naturais de adjetivos antes do substantivo.", "a very cold morning / a sweet person / a young healthy man / a large museum", [["It is a very cold morning.", "É uma manhã muito fria.", "very intensifica cold"], ["She is a sweet person.", "Ela é uma pessoa doce/gentil.", "adjetivo + substantivo"], ["We visited a large museum.", "Nós visitamos um museu grande.", "descrição de lugar"]], "Monte quatro frases-modelo: uma com very, uma pessoa, um objeto e um lugar. Em cada frase, sublinhe o substantivo e circule o adjetivo.", ["a", "very", "cold", "morning", "is", "It"], "It is a very cold morning.", "No Pareto, recupere very, cold, sweet, young, large e museum; combine intensidade e descrição em frases completas."),
  lesson("Cores como adjetivos em descrições", "As cores do original também funcionam como adjetivos. Em inglês, elas vêm antes do nome: a red bag, a blue car. Use a cor para tornar a descrição observável e específica.", "yellow, blue, white, brown, golden, gray, purple, orange, black, silver, red, pink, green, violet", [["She has a red bag.", "Ela tem uma bolsa vermelha.", "cor antes do substantivo"], ["The blue car is outside.", "O carro azul está do lado de fora.", "cor + objeto + lugar"], ["We saw green trees near the beach.", "Nós vimos árvores verdes perto da praia.", "cor em descrição de cena"]], "Descreva cinco objetos ou elementos de uma cena usando cores. Depois, transforme duas descrições em perguntas e respostas curtas.", ["The", "blue", "car", "is", "outside"], "The blue car is outside.", "No Pareto, recupere red, blue, green, black, white e yellow; descreva objetos reais sem trocar a posição de cor e substantivo."),
];
