import type { ParetoCategory, ParetoWord } from "./paretoContent";

type ParetoAddition = readonly [
  ptBR: string,
  enUS: string,
  category: ParetoCategory,
  example: string,
  examplePt: string,
  scene: string,
];

const CORE_ADDITION_ROWS: readonly ParetoAddition[] = [
  // Casa e rotina
  ["Despertador", "Alarm clock", "home", "My alarm clock rings at seven.", "Meu despertador toca às sete.", "home"],
  ["Tapete de entrada", "Doormat", "home", "Leave your shoes on the doormat.", "Deixe seus sapatos no tapete de entrada.", "home"],
  ["Maçaneta", "Door handle", "home", "The door handle is loose.", "A maçaneta está solta.", "home"],
  ["Interruptor", "Light switch", "home", "Turn off the light switch.", "Desligue o interruptor.", "home"],
  ["Tomada", "Power outlet", "home", "The charger is in the power outlet.", "O carregador está na tomada.", "home"],
  ["Cesto de roupa", "Laundry basket", "home", "Put the towels in the laundry basket.", "Coloque as toalhas no cesto de roupa.", "home"],
  ["Cabide", "Clothes hanger", "home", "Hang the jacket on a clothes hanger.", "Pendure a jaqueta em um cabide.", "home"],
  ["Fronha", "Pillowcase", "home", "This pillowcase is clean.", "Esta fronha está limpa.", "home"],
  ["Cortina de banho", "Shower curtain", "home", "Close the shower curtain, please.", "Feche a cortina de banho, por favor.", "home"],
  ["Pia do banheiro", "Bathroom sink", "home", "The bathroom sink needs cleaning.", "A pia do banheiro precisa de limpeza.", "home"],
  ["Sabonete líquido", "Hand soap", "home", "There is hand soap by the sink.", "Há sabonete líquido perto da pia.", "home"],
  ["Papel-toalha", "Paper towel", "home", "Use a paper towel to dry the table.", "Use um papel-toalha para secar a mesa.", "kitchen"],
  ["Filtro de água", "Water filter", "home", "The water filter is full.", "O filtro de água está cheio.", "kitchen"],
  ["Bancada da cozinha", "Kitchen counter", "home", "Keep the kitchen counter clear.", "Mantenha a bancada da cozinha livre.", "kitchen"],
  ["Assadeira", "Baking sheet", "kitchen", "Place the cookies on the baking sheet.", "Coloque os biscoitos na assadeira.", "kitchen"],
  ["Óleo de cozinha", "Cooking oil", "kitchen", "Add a little cooking oil.", "Adicione um pouco de óleo de cozinha.", "kitchen"],
  ["Cubos de gelo", "Ice cubes", "kitchen", "Would you like ice cubes?", "Você gostaria de cubos de gelo?", "kitchen"],
  ["Mesa de café", "Coffee table", "home", "The keys are on the coffee table.", "As chaves estão na mesa de café.", "home"],
  ["Luminária de piso", "Floor lamp", "home", "The floor lamp makes the room warm.", "A luminária de piso deixa o ambiente aconchegante.", "home"],
  ["Espaço de trabalho em casa", "Home office", "work", "She works from her home office.", "Ela trabalha do escritório em casa.", "home"],

  // Pessoas, serviços e comunidade
  ["Centro comunitário", "Community center", "social", "The community center offers free classes.", "O centro comunitário oferece aulas gratuitas.", "city"],
  ["Abrigo de animais", "Animal shelter", "animals", "The animal shelter needs volunteers.", "O abrigo de animais precisa de voluntários.", "city"],
  ["Atendimento ao cliente", "Customer service", "business", "Customer service answered quickly.", "O atendimento ao cliente respondeu rapidamente.", "work"],
  ["Central de atendimento", "Call center", "business", "The call center is open today.", "A central de atendimento está aberta hoje.", "work"],
  ["Balcão de informações", "Information desk", "travel", "Ask at the information desk.", "Pergunte no balcão de informações.", "travel"],
  ["Recepção", "Front desk", "travel", "Please check in at the front desk.", "Faça o check-in na recepção, por favor.", "travel"],
  ["Guichê de serviço", "Service desk", "business", "The service desk can help you.", "O guichê de serviço pode ajudar você.", "work"],
  ["Equipe de suporte", "Support team", "technology", "Our support team is available online.", "Nossa equipe de suporte está disponível on-line.", "technology"],
  ["Contato de emergência", "Emergency contact", "health", "Add an emergency contact to your profile.", "Adicione um contato de emergência ao seu perfil.", "health"],
  ["Primeiros socorros", "First aid", "health", "The teacher knows basic first aid.", "O professor conhece primeiros socorros básicos.", "health"],
  ["Posto policial", "Police station", "city", "The police station is near the park.", "A delegacia fica perto do parque.", "city"],
  ["Biblioteca pública", "Public library", "education", "The public library closes at six.", "A biblioteca pública fecha às seis.", "city"],
  ["Banheiro público", "Public restroom", "travel", "The public restroom is downstairs.", "O banheiro público fica no andar de baixo.", "travel"],
  ["Acesso para cadeira de rodas", "Wheelchair access", "city", "This entrance has wheelchair access.", "Esta entrada tem acesso para cadeira de rodas.", "city"],
  ["Taxa de entrada", "Entrance fee", "travel", "Is there an entrance fee?", "Há taxa de entrada?", "travel"],
  ["Horário de funcionamento", "Opening hours", "business", "Check the opening hours online.", "Verifique o horário de funcionamento on-line.", "city"],
  ["Lista de espera", "Waiting list", "business", "Your name is on the waiting list.", "Seu nome está na lista de espera.", "work"],
  ["Sala de espera", "Waiting room", "health", "Please wait in the waiting room.", "Aguarde na sala de espera, por favor.", "health"],
  ["Sala de reunião", "Meeting room", "work", "The meeting room is on the second floor.", "A sala de reunião fica no segundo andar.", "work"],
  ["Sala da equipe", "Staff room", "work", "Lunch is in the staff room.", "O almoço está na sala da equipe.", "work"],

  // Tecnologia e comunicação
  ["Endereço de e-mail", "Email address", "technology", "Please write your email address here.", "Escreva seu endereço de e-mail aqui, por favor.", "technology"],
  ["Número de telefone", "Phone number", "technology", "Can I have your phone number?", "Posso ter seu número de telefone?", "technology"],
  ["Nome de usuário", "User name", "technology", "Choose a secure user name.", "Escolha um nome de usuário seguro.", "technology"],
  ["Perfil de usuário", "User profile", "technology", "Update your user profile.", "Atualize seu perfil de usuário.", "technology"],
  ["Conta on-line", "Online account", "technology", "Create an online account first.", "Crie uma conta on-line primeiro.", "technology"],
  ["Redefinição de senha", "Password reset", "technology", "Request a password reset by email.", "Solicite a redefinição de senha por e-mail.", "technology"],
  ["Código de confirmação", "Confirmation code", "technology", "Enter the confirmation code.", "Digite o código de confirmação.", "technology"],
  ["Mensagem de texto", "Text message", "technology", "I sent you a text message.", "Enviei uma mensagem de texto para você.", "technology"],
  ["Mensagem de voz", "Voice message", "technology", "Leave a short voice message.", "Deixe uma mensagem de voz curta.", "technology"],
  ["Reunião virtual", "Virtual meeting", "technology", "We have a virtual meeting later.", "Temos uma reunião virtual mais tarde.", "technology"],
  ["Aula em vídeo", "Video lesson", "education", "Watch the video lesson again.", "Assista à aula em vídeo novamente.", "education"],
  ["Aula on-line", "Online class", "education", "The online class starts soon.", "A aula on-line começa em breve.", "education"],
  ["Barra de busca", "Search bar", "technology", "Type the word in the search bar.", "Digite a palavra na barra de busca.", "technology"],
  ["Lista de contatos", "Contact list", "technology", "Add her to your contact list.", "Adicione-a à sua lista de contatos.", "technology"],
  ["Conexão de internet", "Internet access", "technology", "The hotel has internet access.", "O hotel tem acesso à internet.", "travel"],
  ["Plano de dados", "Data plan", "technology", "My data plan is limited.", "Meu plano de dados é limitado.", "technology"],
  ["Carregador de telefone", "Phone charger", "technology", "Do you have a phone charger?", "Você tem um carregador de telefone?", "technology"],
  ["Tela quebrada", "Broken screen", "technology", "The phone has a broken screen.", "O telefone tem uma tela quebrada.", "technology"],
  ["Atualização disponível", "Update available", "technology", "There is an update available.", "Há uma atualização disponível.", "technology"],
  ["Configuração de privacidade", "Privacy setting", "technology", "Review your privacy setting.", "Revise sua configuração de privacidade.", "technology"],

  // Saúde e autocuidado
  ["Consulta médica", "Doctor appointment", "health", "I have a doctor appointment tomorrow.", "Tenho uma consulta médica amanhã.", "health"],
  ["Teste de sangue", "Blood test", "health", "The doctor ordered a blood test.", "O médico solicitou um teste de sangue.", "health"],
  ["Temperatura corporal", "Body temperature", "health", "Check your body temperature.", "Verifique sua temperatura corporal.", "health"],
  ["Alergia alimentar", "Food allergy", "health", "Tell us about any food allergy.", "Informe-nos sobre qualquer alergia alimentar.", "health"],
  ["Medicamento para alergia", "Allergy medicine", "health", "Take your allergy medicine as directed.", "Tome seu medicamento para alergia conforme orientado.", "health"],
  ["Cartão do seguro", "Insurance card", "health", "Bring your insurance card.", "Traga seu cartão do seguro.", "health"],
  ["Exame de saúde", "Health check", "health", "Schedule a yearly health check.", "Agende um exame de saúde anual.", "health"],
  ["Máscara facial", "Face mask", "health", "Wear a face mask if needed.", "Use máscara facial se necessário.", "health"],
  ["Atividade física", "Physical activity", "health", "Daily physical activity helps your mood.", "A atividade física diária ajuda seu humor.", "sports"],
  ["Aula de ginástica", "Fitness class", "sports", "She joined a fitness class.", "Ela entrou em uma aula de ginástica.", "sports"],
  ["Bicicleta ergométrica", "Exercise bike", "sports", "The exercise bike is by the window.", "A bicicleta ergométrica fica perto da janela.", "sports"],
  ["Piscina coberta", "Indoor pool", "sports", "The indoor pool is warm.", "A piscina coberta é aquecida.", "sports"],
  ["Cinto de segurança", "Safety belt", "transport", "Fasten your safety belt.", "Aperte o cinto de segurança.", "transport"],
  ["Regra de segurança", "Safety rule", "education", "Follow every safety rule.", "Siga todas as regras de segurança.", "education"],
  ["Detector de fumaça", "Smoke detector", "home", "Test the smoke detector monthly.", "Teste o detector de fumaça mensalmente.", "home"],
  ["Saída de emergência", "Emergency exit", "travel", "The emergency exit is behind you.", "A saída de emergência fica atrás de você.", "travel"],
  ["Mudança de turno", "Shift change", "work", "The shift change is at noon.", "A troca de turno é ao meio-dia.", "work"],
  ["Turno noturno", "Night shift", "work", "He works the night shift.", "Ele trabalha no turno noturno.", "work"],
  ["Pausa para almoço", "Lunch break", "work", "Let us meet after lunch break.", "Vamos nos encontrar depois da pausa para almoço.", "work"],
  ["Tempo livre", "Free time", "time", "What do you do in your free time?", "O que você faz no seu tempo livre?", "social"],

  // Escola, trabalho e planejamento
  ["Meta de aprendizagem", "Learning goal", "education", "Set one learning goal today.", "Defina uma meta de aprendizagem hoje.", "education"],
  ["Tarefa de escrita", "Writing task", "education", "Complete the writing task tonight.", "Conclua a tarefa de escrita hoje à noite.", "education"],
  ["Lista de leitura", "Reading list", "education", "This book is on my reading list.", "Este livro está na minha lista de leitura.", "education"],
  ["Grupo de estudo", "Study group", "education", "Our study group meets on Friday.", "Nosso grupo de estudo se reúne na sexta-feira.", "education"],
  ["Horário de estudo", "Study time", "education", "Protect your study time.", "Proteja seu horário de estudo.", "education"],
  ["Matéria escolar", "School subject", "education", "English is my favorite school subject.", "Inglês é minha matéria escolar favorita.", "education"],
  ["Aula de arte", "Art class", "arts", "We have art class on Monday.", "Temos aula de arte na segunda-feira.", "education"],
  ["Aula de música", "Music lesson", "arts", "My music lesson is after school.", "Minha aula de música é depois da escola.", "education"],
  ["Depois da aula", "After school", "education", "I practice English after school.", "Pratico inglês depois da aula.", "education"],
  ["Entrevista de emprego", "Job interview", "work", "Prepare for your job interview.", "Prepare-se para sua entrevista de emprego.", "work"],
  ["Horário de trabalho", "Work schedule", "work", "My work schedule changed.", "Meu horário de trabalho mudou.", "work"],
  ["Política da empresa", "Company policy", "work", "Read the company policy carefully.", "Leia a política da empresa com atenção.", "work"],
  ["Prédio de escritórios", "Office building", "work", "The office building is downtown.", "O prédio de escritórios fica no centro.", "city"],
  ["Cadeira de escritório", "Office chair", "work", "Adjust your office chair.", "Ajuste sua cadeira de escritório.", "work"],
  ["Apresentação de slides", "Presentation slide", "work", "The presentation slide is ready.", "O slide da apresentação está pronto.", "work"],
  ["Verificação de qualidade", "Quality check", "work", "The product passed a quality check.", "O produto passou por uma verificação de qualidade.", "work"],
  ["Plano alternativo", "Backup plan", "work", "We need a backup plan.", "Precisamos de um plano alternativo.", "work"],
  ["Tarefa diária", "Daily task", "work", "Finish your daily task first.", "Termine sua tarefa diária primeiro.", "work"],
  ["Reunião de equipe", "Team meeting", "work", "The team meeting begins now.", "A reunião de equipe começa agora.", "work"],
  ["Licença de trabalho", "Work permit", "work", "The work permit expires soon.", "A licença de trabalho vence em breve.", "work"],

  // Viagem e mobilidade
  ["Itinerário de voo", "Flight itinerary", "travel", "Check your flight itinerary tonight.", "Verifique seu itinerário de voo hoje à noite.", "travel"],
  ["Portão de embarque", "Departure gate", "travel", "The departure gate changed.", "O portão de embarque mudou.", "travel"],
  ["Controle de passaporte", "Passport control", "travel", "Passport control is ahead.", "O controle de passaporte fica à frente.", "travel"],
  ["Documento de viagem", "Travel document", "travel", "Keep your travel document safe.", "Mantenha seu documento de viagem seguro.", "travel"],
  ["Seguro de viagem", "Travel insurance", "travel", "Travel insurance gives peace of mind.", "O seguro de viagem traz tranquilidade.", "travel"],
  ["Etiquetas de bagagem", "Luggage tag", "travel", "Write your name on the luggage tag.", "Escreva seu nome na etiqueta de bagagem.", "travel"],
  ["Bagagem perdida", "Lost luggage", "travel", "Report your lost luggage immediately.", "Comunique sua bagagem perdida imediatamente.", "travel"],
  ["Ponto de retirada", "Pickup point", "travel", "Meet me at the pickup point.", "Encontre-me no ponto de retirada.", "travel"],
  ["Ônibus local", "Local bus", "transport", "The local bus stops here.", "O ônibus local para aqui.", "city"],
  ["Rota de ônibus", "Bus route", "transport", "This bus route goes downtown.", "Esta rota de ônibus vai ao centro.", "city"],
  ["Bilhete de ônibus", "Bus ticket", "transport", "Buy a bus ticket first.", "Compre uma passagem de ônibus primeiro.", "city"],
  ["Mapa do metrô", "Subway map", "transport", "Check the subway map.", "Verifique o mapa do metrô.", "city"],
  ["Linha de metrô", "Subway line", "transport", "Take the blue subway line.", "Pegue a linha azul do metrô.", "city"],
  ["Plataforma do trem", "Train platform", "transport", "The train platform is number four.", "A plataforma do trem é a número quatro.", "travel"],
  ["Número da plataforma", "Platform number", "transport", "Look for the platform number.", "Procure o número da plataforma.", "travel"],
  ["Aluguel de carro", "Car rental", "travel", "Car rental is near the airport.", "O aluguel de carro fica perto do aeroporto.", "travel"],
  ["Teste de direção", "Driving test", "transport", "She passed her driving test.", "Ela passou no teste de direção.", "city"],
  ["Sinal de trânsito", "Road sign", "transport", "Read every road sign.", "Leia cada sinal de trânsito.", "city"],
  ["Limite de velocidade", "Speed limit", "transport", "Respect the speed limit.", "Respeite o limite de velocidade.", "city"],
  ["Engarrafamento", "Traffic jam", "transport", "We are late because of a traffic jam.", "Estamos atrasados por causa de um engarrafamento.", "city"],

  // Compras, dinheiro e atendimento
  ["Forma de pagamento", "Payment method", "shopping", "Choose a payment method.", "Escolha uma forma de pagamento.", "shopping"],
  ["Cartão de débito", "Debit card", "finance", "I paid with my debit card.", "Paguei com meu cartão de débito.", "shopping"],
  ["Conta poupança", "Savings account", "finance", "I opened a savings account.", "Abri uma conta poupança.", "finance"],
  ["Transferência de dinheiro", "Money transfer", "finance", "The money transfer is complete.", "A transferência de dinheiro está concluída.", "finance"],
  ["Câmbio de moeda", "Currency exchange", "finance", "The currency exchange is open.", "O câmbio de moeda está aberto.", "finance"],
  ["Saldo devedor", "Balance due", "finance", "Your balance due is on the bill.", "Seu saldo devedor está na conta.", "finance"],
  ["Recibo de venda", "Sales receipt", "shopping", "Keep the sales receipt.", "Guarde o recibo de venda.", "shopping"],
  ["Etiqueta de preço", "Price tag", "shopping", "The price tag is missing.", "A etiqueta de preço está faltando.", "shopping"],
  ["Política de devolução", "Return policy", "shopping", "Ask about the return policy.", "Pergunte sobre a política de devolução.", "shopping"],
  ["Endereço de entrega", "Delivery address", "shopping", "Confirm the delivery address.", "Confirme o endereço de entrega.", "shopping"],
  ["Tempo de entrega", "Delivery time", "shopping", "What is the delivery time?", "Qual é o tempo de entrega?", "shopping"],
  ["Número do pedido", "Order number", "shopping", "Please provide the order number.", "Informe o número do pedido, por favor.", "shopping"],
  ["Taxa extra", "Extra charge", "shopping", "There is no extra charge.", "Não há taxa extra.", "shopping"],
  ["Taxa de cancelamento", "Cancellation fee", "shopping", "The cancellation fee is small.", "A taxa de cancelamento é pequena.", "shopping"],
  ["Carrinho de compras", "Shopping cart", "shopping", "Your shopping cart is empty.", "Seu carrinho de compras está vazio.", "shopping"],
  ["Sacola reutilizável", "Reusable bag", "shopping", "Bring a reusable bag.", "Traga uma sacola reutilizável.", "shopping"],
  ["Loja de roupas", "Clothing store", "shopping", "The clothing store is nearby.", "A loja de roupas fica perto.", "shopping"],
  ["Caixa registradora", "Cash register", "shopping", "Pay at the cash register.", "Pague no caixa registradora.", "shopping"],
  ["Máquina de troco", "Change machine", "shopping", "The change machine accepts coins.", "A máquina de troco aceita moedas.", "city"],
  ["Máquina de vendas", "Vending machine", "shopping", "The vending machine sells drinks.", "A máquina de vendas vende bebidas.", "city"],

  // Cidade, clima e tempo
  ["Centro da cidade", "City center", "city", "The museum is in the city center.", "O museu fica no centro da cidade.", "city"],
  ["Rua lateral", "Side street", "directions", "Turn left on the side street.", "Vire à esquerda na rua lateral.", "city"],
  ["Mercado de rua", "Street market", "shopping", "We buy fruit at the street market.", "Compramos frutas no mercado de rua.", "city"],
  ["Bomba de combustível", "Fuel pump", "transport", "The fuel pump is out of service.", "A bomba de combustível está fora de serviço.", "city"],
  ["Lavanderia", "Dry cleaner", "city", "The dry cleaner opens at eight.", "A lavanderia abre às oito.", "city"],
  ["Oficina de conserto", "Repair shop", "city", "The repair shop fixed my bike.", "A oficina de conserto consertou minha bicicleta.", "city"],
  ["Loja de alimentos", "Grocery store", "shopping", "The grocery store has fresh bread.", "A loja de alimentos tem pão fresco.", "city"],
  ["Praça de alimentação", "Food court", "food", "Let us eat at the food court.", "Vamos comer na praça de alimentação.", "city"],
  ["Lanchonete", "Snack bar", "food", "The snack bar closes soon.", "A lanchonete fecha em breve.", "city"],
  ["Guia de viagem", "Guidebook", "travel", "This guidebook has useful maps.", "Este guia de viagem tem mapas úteis.", "travel"],
  ["Alerta meteorológico", "Weather alert", "weather", "The weather alert warns about rain.", "O alerta meteorológico avisa sobre chuva.", "weather"],
  ["Relatório do tempo", "Weather report", "weather", "Listen to the weather report.", "Ouça o relatório do tempo.", "weather"],
  ["Fuso horário", "Time zone", "time", "Brazil has more than one time zone.", "O Brasil tem mais de um fuso horário.", "travel"],
  ["Rotina da manhã", "Morning routine", "time", "My morning routine starts with water.", "Minha rotina da manhã começa com água.", "home"],
  ["Plano de fim de semana", "Weekend plan", "time", "What is your weekend plan?", "Qual é seu plano para o fim de semana?", "social"],
  ["Luz natural", "Natural light", "home", "This room has natural light.", "Este quarto tem luz natural.", "home"],
  ["Capa de chuva", "Raincoat", "clothes", "Take your raincoat today.", "Leve sua capa de chuva hoje.", "weather"],
  ["Assento na janela", "Window seat", "travel", "I prefer a window seat.", "Prefiro um assento na janela.", "travel"],
  ["Roteiro a pé", "Walking tour", "travel", "The walking tour starts at ten.", "O roteiro a pé começa às dez.", "city"],
  ["Caminho de caminhada", "Walking path", "nature", "The walking path is safe.", "O caminho de caminhada é seguro.", "nature"],

  // Relações, frases e autonomia
  ["Cartão de aniversário", "Birthday card", "social", "I bought a birthday card.", "Comprei um cartão de aniversário.", "shopping"],
  ["Foto de família", "Family photo", "family", "This family photo is old.", "Esta foto de família é antiga.", "home"],
  ["Membro da família", "Family member", "family", "Every family member is welcome.", "Todo membro da família é bem-vindo.", "home"],
  ["Cuidado infantil", "Child care", "family", "Child care is available here.", "O cuidado infantil está disponível aqui.", "city"],
  ["Quarto de hóspedes", "Guest room", "home", "The guest room is ready.", "O quarto de hóspedes está pronto.", "home"],
  ["Chave reserva", "Spare key", "home", "Keep a spare key with a friend.", "Guarde uma chave reserva com um amigo.", "home"],
  ["Chave da caixa de correio", "Mailbox key", "home", "I cannot find the mailbox key.", "Não encontro a chave da caixa de correio.", "home"],
  ["Cartão da biblioteca", "Library card", "education", "Use your library card to borrow books.", "Use seu cartão da biblioteca para pegar livros.", "education"],
  ["Cartão de estudante", "Student card", "education", "Show your student card at the entrance.", "Mostre seu cartão de estudante na entrada.", "education"],
  ["Crachá", "Name tag", "work", "Wear your name tag at work.", "Use seu crachá no trabalho.", "work"],
  ["Formulário de inscrição", "Application form", "work", "Complete the application form.", "Preencha o formulário de inscrição.", "work"],
  ["Formulário de feedback", "Feedback form", "education", "Please fill in the feedback form.", "Preencha o formulário de feedback, por favor.", "education"],
  ["Dados pessoais", "Personal data", "technology", "Protect your personal data.", "Proteja seus dados pessoais.", "technology"],
  ["Lista de compras", "Grocery list", "shopping", "Write a grocery list before leaving.", "Escreva uma lista de compras antes de sair.", "shopping"],
  ["Plano de refeições", "Meal plan", "food", "Our meal plan includes vegetables.", "Nosso plano de refeições inclui vegetais.", "food"],
  ["Reserva de mesa", "Table reservation", "food", "I made a table reservation.", "Fiz uma reserva de mesa.", "food"],
  ["Número do quarto", "Room number", "travel", "What is your room number?", "Qual é o número do seu quarto?", "travel"],
  ["Chave do quarto", "Room key", "travel", "Do not lose your room key.", "Não perca a chave do quarto.", "travel"],
  ["Serviço de quarto", "Room service", "travel", "Room service is available until midnight.", "O serviço de quarto está disponível até meia-noite.", "travel"],
  ["Telefone público", "Public phone", "city", "The public phone is out of order.", "O telefone público está fora de serviço.", "city"],

  // Ações e expressões funcionais
  ["Registrar presença", "Sign in", "travel", "Please sign in at the desk.", "Registre sua presença no balcão, por favor.", "travel"],
  ["Saída do hotel", "Hotel departure", "travel", "Hotel departure is at noon.", "A saída do hotel é ao meio-dia.", "travel"],
  ["Pegar o elevador", "Take the elevator", "directions", "Take the elevator to floor five.", "Pegue o elevador até o quinto andar.", "city"],
  ["Virar à direita", "Turn right", "directions", "Turn right at the corner.", "Vire à direita na esquina.", "city"],
  ["Seguir em frente", "Go straight ahead", "directions", "Go straight ahead for two blocks.", "Siga em frente por dois quarteirões.", "city"],
  ["Preencher", "Fill out", "actions", "Fill out this short form.", "Preencha este formulário curto.", "work"],
  ["Fazer upload", "Upload", "technology", "Upload your document here.", "Envie seu documento aqui.", "technology"],
  ["Fazer download", "Download", "technology", "Download the lesson for later.", "Baixe a lição para mais tarde.", "technology"],
  ["Entrar em contato", "Get in touch", "social", "Get in touch when you arrive.", "Entre em contato quando chegar.", "social"],
  ["Dar um retorno", "Give feedback", "education", "Give feedback after the class.", "Dê um retorno depois da aula.", "education"],
  ["Pedir esclarecimento", "Ask for clarification", "education", "Ask for clarification when needed.", "Peça esclarecimento quando necessário.", "education"],
  ["Avaliar opções", "Weigh options", "work", "Weigh options before you choose.", "Avalie as opções antes de escolher.", "work"],
  ["Resolver um problema", "Solve a problem", "work", "We can solve this problem together.", "Podemos resolver este problema juntos.", "work"],
  ["Manter contato", "Stay in touch", "social", "Let us stay in touch.", "Vamos manter contato.", "social"],
  ["Cuidar de", "Care for", "family", "Care for your health.", "Cuide da sua saúde.", "health"],
  ["Buscar", "Search for", "actions", "Search for the blue sign.", "Busque a placa azul.", "city"],
  ["Guardar", "Put away", "actions", "Put away your phone during class.", "Guarde seu telefone durante a aula.", "education"],
  ["Resolver agora", "Handle it now", "work", "We can handle it now.", "Podemos resolver isso agora.", "work"],
  ["Tentar novamente", "Try again", "education", "Try again with a slower voice.", "Tente novamente com uma voz mais lenta.", "education"],
  ["Dar um passo", "Take a step", "education", "Take a step toward your goal.", "Dê um passo em direção à sua meta.", "education"],

  // Consulta, prática e revisão
  ["Palavra-chave", "Key word", "education", "Underline the key word.", "Sublinhe a palavra-chave.", "education"],
  ["Frase de exemplo", "Example sentence", "education", "Read the example sentence aloud.", "Leia a frase de exemplo em voz alta.", "education"],
  ["Tradução nativa", "Native translation", "education", "Check the native translation.", "Verifique a tradução nativa.", "education"],
  ["Pronúncia lenta", "Slow pronunciation", "education", "Use slow pronunciation first.", "Use a pronúncia lenta primeiro.", "education"],
  ["Repetição espaçada", "Spaced repetition", "education", "Spaced repetition builds memory.", "A repetição espaçada constrói memória.", "education"],
  ["Recuperação ativa", "Active recall", "education", "Active recall strengthens learning.", "A recuperação ativa fortalece o aprendizado.", "education"],
  ["Resposta escrita", "Written answer", "education", "Write a complete written answer.", "Escreva uma resposta escrita completa.", "education"],
  ["Frase completa", "Complete sentence", "education", "Answer with a complete sentence.", "Responda com uma frase completa.", "education"],
  ["Pergunta de revisão", "Review question", "education", "Answer the review question.", "Responda à pergunta de revisão.", "education"],
  ["Prática de conversa", "Conversation practice", "education", "Conversation practice builds confidence.", "A prática de conversa cria confiança.", "education"],
  ["Ponto fraco", "Weak point", "education", "This exercise helps a weak point.", "Este exercício ajuda um ponto fraco.", "education"],
  ["Próxima etapa", "Next step", "education", "Choose your next step.", "Escolha sua próxima etapa.", "education"],
  ["Objetivo pessoal", "Personal goal", "education", "Your personal goal is important.", "Seu objetivo pessoal é importante.", "education"],
  ["Progresso diário", "Daily progress", "education", "Review your daily progress.", "Revise seu progresso diário.", "education"],
  ["Lembrete de revisão", "Review reminder", "education", "Set a review reminder.", "Defina um lembrete de revisão.", "education"],
  ["Prática guiada", "Guided practice", "education", "Start the guided practice now.", "Inicie a prática guiada agora.", "education"],
  ["Uso real", "Real use", "education", "Practice the word in real use.", "Pratique a palavra em uso real.", "education"],
  ["Explicação clara", "Clear explanation", "education", "Ask for a clear explanation.", "Peça uma explicação clara.", "education"],
  ["Ajuda de estudo", "Study help", "education", "Open study help when needed.", "Abra a ajuda de estudo quando necessário.", "education"],
  ["Livro de consulta", "Reference book", "education", "Use the reference book for support.", "Use o livro de consulta como apoio.", "education"],
];

export const PARETO_CORE_ADDITIONS: ParetoWord[] = CORE_ADDITION_ROWS.map((row, index) => ({
  id: `core-${String(index + 1).padStart(3, "0")}`,
  ptBR: row[0],
  enUS: row[1],
  pronunciation: row[1],
  category: row[2],
  frequency: 7,
  example: row[3],
  examplePt: row[4],
  scene: row[5],
}));
