export type EnglishSceneVocabulary = {
  title: string;
  titlePt: string;
  terms: Array<{ label: string; translation: string }>;
};

export const PT_BR_ENGLISH_REMAINING_VOCABULARY: Record<string, EnglishSceneVocabulary> = {
  garden: { title: "Japanese Garden", titlePt: "Jardim Japonês", terms: [{ label: "Cherry Blossom", translation: "Flor de cerejeira" }, { label: "Pond", translation: "Lago" }, { label: "Bridge", translation: "Ponte" }, { label: "Stone", translation: "Pedra" }, { label: "Bamboo", translation: "Bambu" }, { label: "Lantern", translation: "Lanterna" }] },
  cafe: { title: "Parisian Cafe", titlePt: "Café Parisiense", terms: [{ label: "Coffee", translation: "Café" }, { label: "Croissant", translation: "Croissant" }, { label: "Waiter", translation: "Garçom" }, { label: "Terrace", translation: "Terraço" }, { label: "Newspaper", translation: "Jornal" }, { label: "Bill", translation: "Conta" }] },
  paris: { title: "Paris", titlePt: "Paris", terms: [{ label: "Eiffel Tower", translation: "Torre Eiffel" }, { label: "Cafe", translation: "Café" }, { label: "Street", translation: "Rua" }, { label: "Flower", translation: "Flor" }, { label: "Building", translation: "Prédio" }, { label: "Sky", translation: "Céu" }, { label: "Bakery", translation: "Padaria" }, { label: "Bridge", translation: "Ponte" }] },
  kitchen: { title: "Kitchen", titlePt: "Cozinha", terms: [{ label: "Refrigerator", translation: "Geladeira" }, { label: "Oven", translation: "Forno" }, { label: "Table", translation: "Mesa" }, { label: "Window", translation: "Janela" }, { label: "Spoon", translation: "Colher" }, { label: "Counter", translation: "Bancada" }] },
  restaurant: { title: "Restaurant", titlePt: "Restaurante", terms: [{ label: "Pasta", translation: "Massa" }, { label: "Wine", translation: "Vinho" }, { label: "Table", translation: "Mesa" }, { label: "Candle", translation: "Vela" }, { label: "Picture", translation: "Quadro" }, { label: "Window", translation: "Janela" }] },
  supermarket: { title: "Supermarket", titlePt: "Supermercado", terms: [{ label: "Cart", translation: "Carrinho" }, { label: "Fruit", translation: "Fruta" }, { label: "Bread", translation: "Pão" }, { label: "Milk", translation: "Leite" }, { label: "Checkout", translation: "Caixa" }, { label: "Price", translation: "Preço" }] },
  tokyo: { title: "Tokyo", titlePt: "Tóquio", terms: [{ label: "Mount Fuji", translation: "Monte Fuji" }, { label: "Street", translation: "Rua" }, { label: "Advertisement", translation: "Publicidade" }, { label: "Screen", translation: "Tela" }, { label: "Building", translation: "Prédio" }, { label: "Sign", translation: "Placa" }] },
  medieval: { title: "Medieval Market", titlePt: "Mercado Medieval", terms: [{ label: "Castle", translation: "Castelo" }, { label: "Market", translation: "Mercado" }, { label: "Knight", translation: "Cavaleiro" }, { label: "Flag", translation: "Bandeira" }, { label: "Fountain", translation: "Poço" }, { label: "Candle", translation: "Vela" }] },
  port: { title: "Mediterranean Port", titlePt: "Porto Mediterrâneo", terms: [{ label: "Boat", translation: "Barco" }, { label: "Sea", translation: "Mar" }, { label: "Lighthouse", translation: "Farol" }, { label: "Seagull", translation: "Gaivota" }, { label: "Net", translation: "Rede" }, { label: "Anchor", translation: "Âncora" }] },
  museum: { title: "Art Museum", titlePt: "Museu de Arte", terms: [{ label: "Painting", translation: "Quadro" }, { label: "Sculpture", translation: "Escultura" }, { label: "Frame", translation: "Moldura" }, { label: "Visitor", translation: "Visitante" }, { label: "Gallery", translation: "Galeria" }, { label: "Light", translation: "Luz" }] },
  park: { title: "City Park", titlePt: "Parque da Cidade", terms: [{ label: "Tree", translation: "Árvore" }, { label: "Playground", translation: "Brinquedos" }, { label: "Fountain", translation: "Fonte" }, { label: "People", translation: "Pessoas" }, { label: "Dog", translation: "Cachorro" }, { label: "Grass", translation: "Grama" }] },
  mountain: { title: "Mountain", titlePt: "Montanha", terms: [{ label: "Peak", translation: "Cume" }, { label: "Snow", translation: "Neve" }, { label: "Forest", translation: "Floresta" }, { label: "Rock", translation: "Rocha" }, { label: "Cloud", translation: "Nuvem" }, { label: "Lake", translation: "Lago" }] },
};
