import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const protectedContent = readFileSync(path.join(root, "server/curriculum/abcBookContent.ts"), "utf8");
const bookPage = readFileSync(path.join(root, "client/src/pages/ABCBook.tsx"), "utf8");

describe("ficha de termo do Livro ABC", () => {
  it("mantém os campos pedagógicos no contrato curricular protegido", () => {
    expect(protectedContent).toContain("termCard:");
    expect(protectedContent).toContain('term: "need"');
    expect(protectedContent).toContain("grammar:");
    expect(protectedContent).toContain("pronunciation:");
    expect(protectedContent).toContain("paretoPrompt:");
    expect(protectedContent).toContain("additionalTermCards:");
    expect(protectedContent).toContain('term: "help"');
    expect(protectedContent).toContain('term: "water"');
    expect(protectedContent).toContain('term: "where"');
    expect(protectedContent).toContain('term: "airport"');
    expect(protectedContent).toContain('term: "friend"');
    expect(protectedContent).toContain('term: "morning"');
    expect(protectedContent).toContain('term: "study"');
    expect(protectedContent).toContain('term: "tomorrow"');
    expect(protectedContent).toContain('term: "book"');
    expect(protectedContent).toContain('term: "work"');
    expect(protectedContent).toContain('term: "can"');
    expect(protectedContent).toContain('term: "please"');
    expect(protectedContent).toContain('term: "hello"');
    expect(protectedContent).toContain('term: "thank you"');
    expect(protectedContent).toContain('term: "sorry"');
    expect(protectedContent).toContain('term: "again"');
    expect(protectedContent).toContain('term: "slowly"');
    expect(protectedContent).toContain('term: "understand"');
    expect(protectedContent).toContain('term: "learn"');
    expect(protectedContent).toContain('term: "today"');
    expect(protectedContent).toContain('term: "name"');
    expect(protectedContent).toContain('term: "from"');
    expect(protectedContent).toContain('pronunciation: string');
    expect(protectedContent).toContain('pronunciation: "/ˈstʌd.i/"');
    expect(protectedContent).toContain("A1_CHAPTERS");
    expect(protectedContent).toContain('title: "Escute, repita e responda"');
    expect(protectedContent).toContain('title: "Escreva, corrija e reveja"');
    expect(protectedContent).toContain('title: "Som e escrita caminham juntos"');
    expect(protectedContent).toContain("STRUCTURED_A1_UNITS");
    expect(protectedContent).toContain("chapters: A1_CHAPTERS");
    expect(protectedContent).toContain("memorySteps:");
    expect(protectedContent).toContain('title: "7. Revise com Pareto"');
    expect(protectedContent).toContain("sentenceStructure:");
    expect(protectedContent).toContain('title: "Da ideia à frase: português e inglês"');
    expect(protectedContent).toContain("contextGroups:");
    expect(protectedContent).toContain('title: "Contexto 1 — Família"');
    expect(protectedContent).toContain('title: "Contexto 2 — Círculo social"');
    expect(protectedContent).toContain("alphabetLetters:");
    expect(protectedContent).toContain('letter: "A"');
    expect(protectedContent).toContain("soundLessons:");
    expect(protectedContent).toContain('title: "A em palavra curta"');
    expect(protectedContent).toContain("isPortugueseEnglish");
    expect(protectedContent).toContain("available: false");
  });

  it("renderiza a ficha simples a partir da entrega protegida, sem duplicar o termo no cliente", () => {
    expect(bookPage).toContain("Ficha de termo");
    expect(bookPage).toContain("book.termCard.term");
    expect(bookPage).toContain("book.termCard.paretoPrompt");
    expect(bookPage).toContain("book.additionalTermCards.map");
    expect(bookPage).toContain("playNativeReference(card.term)");
    expect(bookPage).toContain("book.chapters.map");
    expect(bookPage).toContain("book.memorySteps");
    expect(bookPage).toContain("book.sentenceStructure");
    expect(bookPage).toContain("book.contextGroups");
    expect(bookPage).toContain("book.alphabetLetters");
    expect(bookPage).toContain("book.soundLessons");
    expect(bookPage).toContain("Capítulos contínuos para estudar");
    expect(bookPage).toContain("chapter.writingPrompt");
    expect(bookPage).toContain("/base-de-estudos?unit=");
    expect(bookPage).toContain('aria-label="Sumário dos capítulos A1"');
    expect(bookPage).toContain('id="sumario-a1"');
    expect(bookPage).toContain('onClick={() => goToChapter(`capitulo-a1-${index + 1}`)}');
    expect(bookPage).toContain('scrollIntoView({ behavior: "smooth", block: "nearest", inline: "start" })');
    expect(bookPage).toContain('const chapterId = `capitulo-a1-${index + 1}`');
    expect(bookPage).toContain("id={chapterId}");
    expect(bookPage).toContain('href="#sumario-a1"');
    expect(bookPage).toContain("const chapterParetoHref");
    expect(bookPage).toContain("Praticar no Pareto");
    expect(bookPage).toContain("${paretoReturnTo}#${chapterId}");
    expect(bookPage).toContain("const chapterTeacherHref");
    expect(bookPage).toContain("/free-talk?returnTo=");
    expect(bookPage).toContain("Falar com o Professor");
    expect(bookPage).toContain("if (!book.available)");
    expect(bookPage).toContain("Edição em preparação");
    expect(bookPage).not.toContain('const TERM_CARD');
  });
});
